"""Build datalog/existential.dl — "Some/Most <X> are/have/include <Y>" claims (and soft "<X> may be
<Y>" pointers) as existential facts, from rules.txt.

These are broad (non-universal) assertions transpile's _some_are abstains on (coordinated predicate,
complex object) — and "may"-modal pointers whose subject/modal is buried mid-sentence so the permission
parser misses them (e.g. 202.2f "Effects may change an object's color", 118.7 "What a player needs to
do to pay a cost may be changed or reduced by effects"). They're real — a SUBSET of X has/may-have
property Y — just not crisp universal rules. Captured as existential(subject, property): "some
continuous effects are replacement effects" is faithful as existential(continuous_effect,
replacement_effect). Curated per rule (anchored regex + subject/property slug, abstaining if reworded),
so the fuzziness is recorded as data rather than left as a false "uncovered".
"""

from __future__ import annotations

import re
from pathlib import Path

from dlgen import Program
from rules_parser import split
from transpile import _split_sentences

# (rule, anchor regex, subject, [properties])
_RULES = [
    ("609.6", r"^Some continuous effects are replacement effects or prevention effects",
     "continuous_effect", ["replacement_effect", "prevention_effect"]),
    ("200.3", r"^Some objects that aren.t cards .* have some of the parts of a card",
     "noncard_object", ["some_card_parts"]),
    ("603.6e", r"^Some Auras have triggered abilities that trigger on the enchanted permanent leaving the battlefield",
     "aura", ["leaves_battlefield_triggered_ability"]),
    ("615.9", r"^Some effects generated by the resolution of a spell or ability prevent damage from a source of a player.s choice",
     "effect", ["prevent_damage_from_chosen_source"]),
    ("603.5", r"^Some triggered abilities. effects are optional",
     "triggered_ability_effect", ["optional"]),
    ("614.17d", r"^Some [“\"]can.t[”\"] effects modify how a permanent enters the battlefield",
     "cant_effect", ["modifies_how_permanent_enters"]),
    ("601.3e", r"^Some rules and effects state that an alternative set of characteristics or a subset of characteristics are considered",
     "rule_or_effect", ["uses_alternative_characteristics"]),
    ("118.4", r"^Some costs include an [“\"{]?X",
     "cost", ["x_amount"]),
    ("716.4", r"^Some older creature cards, called leveler cards, have level up abilities",
     "leveler_card", ["level_up_ability"]),
    ("702.104b", r"^Objects with tribute have triggered abilities that check",
     "object_with_tribute", ["tribute_not_paid_check_trigger"]),
    ("202.2f", r"^Effects may change an object.s color",
     "effect", ["may_change_object_color"]),
    # a soft "may"-pointer whose modal is buried mid-sentence (subject is a free-relative clause).
    ("118.7", r"^What a player actually needs to do to pay a cost may be changed or reduced by effects",
     "cost_payment_requirement", ["may_be_changed_or_reduced_by_effects"]),
    # a "Most <X> <verb> <Y>" generality the engine can't take as universal (most abilities, not all).
    ("702.1", r"^Most abilities describe exactly what they do in the card.s rules text",
     "ability", ["usually_describes_what_it_does_in_card_rules_text"]),
]


def _scan():
    text = {sr.number: _split_sentences(sr.text)[0]
            for s in split(Path("rules.txt").read_text(encoding="utf-8")).sections
            for g in s.groups for r in g.rules for sr in [r] + r.subrules}
    return [e for e in _RULES if re.search(e[1], text.get(e[0], ""), re.I)]


def rule_numbers() -> set:
    return {e[0] for e in _scan()}


def build() -> tuple[str, dict]:
    rows = _scan()
    p = Program()
    p.comment("existential.dl — 'Some/Most X are/have/include Y' claims as existential facts, from rules.txt.")
    p.comment("existential(subject, property). GENERATED.")
    p.blank()
    p.decl("existential", [("subject", "symbol"), ("property", "symbol")])
    p.blank()
    seen = set()
    for _n, _pat, subj, props in rows:
        for prop in props:
            if (subj, prop) not in seen:
                seen.add((subj, prop))
                p.fact(f'existential("{subj}", "{prop}")')
    p.blank()
    p.output("existential")
    p.blank()
    p.comment("conformance — spot-check an existential claim the rules state plainly")
    p.conformance(
        [("expect_exist", [("subject", "symbol"), ("property", "symbol")])],
        [("exist", "expect_exist(S, P)", "miss", "existential(S, P)")])
    p.fact('expect_exist("continuous_effect", "replacement_effect")')
    return p.text(), {"total": len(rows)}


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    source, report = build()
    Path("datalog/existential.dl").write_text(source, encoding="utf-8")
    print(f"wrote datalog/existential.dl ({report['total']} rules)")


if __name__ == "__main__":
    main()
