"""Build datalog/cast.dl deterministically from explicit structures.

§117.1a (timing), §405 (the LIFO stack), §601 (casting), §608 (resolution).
"""

from __future__ import annotations

from pathlib import Path

from dlgen import Program
from build_enumerations import members
from build_turn_actions import main_phases

# INTERPRETED from rules.txt (§110.4 permanent types, §505.1 main phases) — not hardcoded.
PERMANENT_TYPES = members("permanent_type")
MAIN_PHASES = main_phases()

INPUTS = [
    ("g_active", [("g", "symbol"), ("p", "symbol")]),
    ("g_step", [("g", "symbol"), ("step", "symbol")]),
    ("g_priority", [("g", "symbol"), ("p", "symbol")]),
    ("g_stack_empty", [("g", "symbol")]),
    ("g_all_passed", [("g", "symbol")]),
    ("in_hand", [("g", "symbol"), ("p", "symbol"), ("s", "symbol")]),
    ("stack", [("g", "symbol"), ("o", "symbol"), ("pos", "number")]),
    ("card_type", [("o", "symbol"), ("t", "symbol")]),
]

EXPECT_DECLS = [
    ("expect_can_cast", [("g", "symbol"), ("p", "symbol"), ("s", "symbol")]),
    ("expect_no_cast", [("g", "symbol"), ("p", "symbol"), ("s", "symbol")]),
    ("expect_top", [("g", "symbol"), ("o", "symbol")]),
    ("expect_resolves", [("g", "symbol"), ("o", "symbol")]),
    ("expect_battlefield", [("g", "symbol"), ("o", "symbol")]),
    ("expect_graveyard", [("g", "symbol"), ("o", "symbol")]),
]
CHECKS = [
    ("can_cast", "expect_can_cast(G, P, S)", "miss", "can_cast(G, P, S)"),
    ("no_cast", "expect_no_cast(G, P, S)", "hit", "can_cast(G, P, S)"),
    ("top", "expect_top(G, O)", "miss", "stack_top(G, O)"),
    ("resolves", "expect_resolves(G, O)", "miss", "resolves(G, O)"),
    ("battlefield", "expect_battlefield(G, O)", "miss", "enters_battlefield(G, O)"),
    ("graveyard", "expect_graveyard(G, O)", "miss", "resolves_to_graveyard(G, O)"),
]

SCENARIOS = [
    'card_type("bolt", "instant")', 'card_type("wrath", "sorcery")', 'card_type("bear_spell", "creature")',
    # g1: bob's turn, combat, alice has priority -> instant any time, sorcery no.
    'g_active("g1", "bob")', 'g_step("g1", "begin_combat")', 'g_priority("g1", "alice")', 'g_stack_empty("g1")',
    'in_hand("g1", "alice", "bolt")', 'in_hand("g1", "alice", "wrath")',
    'expect_can_cast("g1", "alice", "bolt")', 'expect_no_cast("g1", "alice", "wrath")',
    # g2: alice's main phase, empty stack -> sorcery ok.
    'g_active("g2", "alice")', 'g_step("g2", "precombat_main")', 'g_priority("g2", "alice")', 'g_stack_empty("g2")',
    'in_hand("g2", "alice", "wrath")', 'expect_can_cast("g2", "alice", "wrath")',
    # g3: alice's main phase but stack not empty -> sorcery no, instant yes.
    'g_active("g3", "alice")', 'g_step("g3", "precombat_main")', 'g_priority("g3", "alice")',
    'in_hand("g3", "alice", "wrath")', 'in_hand("g3", "alice", "bolt")',
    'expect_no_cast("g3", "alice", "wrath")', 'expect_can_cast("g3", "alice", "bolt")',
    # g4: [bolt@0, wrath@1] all pass -> wrath resolves to graveyard.
    'stack("g4", "bolt", 0)', 'stack("g4", "wrath", 1)', 'g_all_passed("g4")',
    'expect_top("g4", "wrath")', 'expect_resolves("g4", "wrath")', 'expect_graveyard("g4", "wrath")',
    # g5: a creature spell resolves -> battlefield (608.3).
    'stack("g5", "bear_spell", 0)', 'g_all_passed("g5")',
    'expect_resolves("g5", "bear_spell")', 'expect_battlefield("g5", "bear_spell")',
]


def build() -> str:
    p = Program()
    p.comment("cast.dl — GENERATED by build_cast.py (deterministic). Do not edit by hand.")
    p.comment("MTG casting (§601), the stack (§405), resolution (§608), timing (§117.1a).")
    p.blank()
    p.decl("permanent_type", [("t", "symbol")])
    p.facts([f'permanent_type("{t}")' for t in PERMANENT_TYPES])
    p.decl("main_phase_step", [("name", "symbol")])
    p.facts([f'main_phase_step("{m}")' for m in MAIN_PHASES])
    p.blank()
    for name, cols in INPUTS:
        p.decl(name, cols)
    p.blank()

    p.decl("is_instant", [("o", "symbol")])
    p.rule("is_instant(O)", ['card_type(O, "instant")'])
    p.decl("permanent_spell", [("o", "symbol")])
    p.rule("permanent_spell(O)", ["card_type(O, T)", "permanent_type(T)"],
           note="§110.4b — becomes a permanent on resolution")
    p.blank()
    p.decl("can_cast", [("g", "symbol"), ("p", "symbol"), ("s", "symbol")])
    p.rule("can_cast(G, P, S)", ["in_hand(G, P, S)", "g_priority(G, P)", "is_instant(S)"],
           note="§117.1a — an instant, any time you have priority")
    p.rule("can_cast(G, P, S)",
           ["in_hand(G, P, S)", "g_priority(G, P)", "!is_instant(S)",
            "g_active(G, P)", "g_step(G, St)", "main_phase_step(St)", "g_stack_empty(G)"],
           note="§117.1a — a noninstant, only in your main phase + empty stack")
    p.blank()
    p.decl("stack_top", [("g", "symbol"), ("o", "symbol")])
    p.rule("stack_top(G, O)", ["stack(G, O, Pos)", "Pos = max P : { stack(G, _, P) }"],
           note="§405.2/.5 — the top is the last-added object")
    p.decl("resolves", [("g", "symbol"), ("o", "symbol")])
    p.rule("resolves(G, O)", ["stack_top(G, O)", "g_all_passed(G)"],
           note="§608.1 — the top resolves when all players pass")
    p.decl("enters_battlefield", [("g", "symbol"), ("o", "symbol")])
    p.rule("enters_battlefield(G, O)", ["resolves(G, O)", "permanent_spell(O)"], note="§608.3")
    p.decl("resolves_to_graveyard", [("g", "symbol"), ("o", "symbol")])
    p.rule("resolves_to_graveyard(G, O)", ["resolves(G, O)", "!permanent_spell(O)"], note="§608.2")
    p.blank()
    p.output("can_cast", "stack_top", "resolves", "enters_battlefield")
    p.blank()
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()
    p.comment("scenarios under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/cast.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/cast.dl")


if __name__ == "__main__":
    main()
