"""Build datalog/sba_demo.dl — state-based actions applied UNTIL STABLE, in Datalog.

§704.3: SBAs are checked, applied, and re-checked repeatedly until none apply.
That is a state TRANSITION (objects leave the battlefield), which pure Souffle
can't do by mutation. We model it with an explicit, bounded timestep, STAGED into
per-step predicates (present_0, present_1, ...) so the frame axiom's negation
isn't a recursive cycle (Souffle stratifies by predicate, not by value).

Cascade demonstrated in ONE run: `thrall` is a 2/2 with two -1/-1 counters (base
0/0) kept alive at 1/1 by `lord`'s +1/+1 anthem. `lord` has lethal combat damage,
so it dies in SBA round 0; with the anthem gone, `thrall` recomputes to 0/0 and
dies in round 1. `bystander` is untouched.
"""

from __future__ import annotations

from pathlib import Path

from dlgen import Program

MAX = 3   # SBA rounds 0..MAX (more than enough to reach a fixpoint here)

INPUTS = [
    ("init_present", [("c", "symbol")]),                 # creatures on the battlefield at round 0
    ("printed_toughness", [("c", "symbol"), ("n", "number")]),
    ("counter", [("c", "symbol"), ("kind", "symbol"), ("n", "number")]),
    ("grants_anthem", [("c", "symbol")]),                # gives other creatures you control +1/+1
    ("controls", [("p", "symbol"), ("c", "symbol")]),
    ("marked", [("c", "symbol"), ("n", "number")]),      # combat damage already marked
]

EXPECT_DECLS = [
    ("expect_dies_step", [("c", "symbol"), ("s", "number")]),
    ("expect_dead", [("c", "symbol")]),
    ("expect_survives", [("c", "symbol")]),
]
CHECKS = [
    ("dies_step", "expect_dies_step(C, S)", "miss", "dies_step(C, S)", "C", '"-"'),
    ("dead", "expect_dead(C)", "miss", "dead(C)"),
    ("survives", "expect_survives(C)", "hit", "dead(C)"),
]

SCENARIOS = [
    'init_present("lord")', 'init_present("thrall")', 'init_present("bystander")',
    # lord: 2/2 anthem, with lethal combat damage marked -> dies SBA round 0.
    'printed_toughness("lord", 2)', 'grants_anthem("lord")', 'controls("alice", "lord")', 'marked("lord", 2)',
    # thrall: 2/2 with two -1/-1 counters -> base 0/0, alive only via the anthem (1/1).
    'printed_toughness("thrall", 2)', 'counter("thrall", "m1m1", 2)', 'controls("alice", "thrall")',
    # bystander: a healthy 3/3, untouched.
    'printed_toughness("bystander", 3)', 'controls("alice", "bystander")',
    'expect_dies_step("lord", 0)', 'expect_dies_step("thrall", 1)',   # the two cascading rounds
    'expect_dead("lord")', 'expect_dead("thrall")', 'expect_survives("bystander")',
]


def build() -> str:
    p = Program()
    p.comment("sba_demo.dl — GENERATED by build_sba_demo.py (deterministic). Do not edit by hand.")
    p.comment("§704.3 — state-based actions applied UNTIL STABLE, as a bounded staged timestep loop.")
    p.blank()
    for name, cols in INPUTS:
        p.decl(name, cols)
    p.blank()
    # -1/-1 counters are static across the SBA loop.
    p.decl("m1m1", [("c", "symbol"), ("m", "number")])
    p.rule("m1m1(C, M)", ["init_present(C)", 'M = sum X : { counter(C, "m1m1", X) }'])
    p.blank()
    p.decl("present_0", [("c", "symbol")])
    p.rule("present_0(C)", ["init_present(C)"])
    p.blank()

    for i in range(MAX + 1):
        p.comment(f"--- SBA round {i} ---")
        # §613.4 — recompute toughness at this round: printed - (-1/-1) + (+1/+1 anthems present now).
        p.decl(f"anthem_src_{i}", [("b", "symbol"), ("l", "symbol")])
        p.rule(f"anthem_src_{i}(B, L)",
               [f"present_{i}(L)", "grants_anthem(L)", "controls(P, L)", "controls(P, B)", "B != L", f"present_{i}(B)"])
        p.decl(f"anthem_n_{i}", [("c", "symbol"), ("a", "number")])
        p.rule(f"anthem_n_{i}(C, A)", [f"present_{i}(C)", f"A = count : {{ anthem_src_{i}(C, _) }}"])
        p.decl(f"toughness_{i}", [("c", "symbol"), ("n", "number")])
        p.rule(f"toughness_{i}(C, N)",
               [f"present_{i}(C)", "printed_toughness(C, Pt)", "m1m1(C, M)", f"anthem_n_{i}(C, A)", "N = Pt - M + A"])
        # SBAs at this round.
        p.decl(f"dies_{i}", [("c", "symbol")])
        p.rule(f"dies_{i}(C)", [f"present_{i}(C)", f"toughness_{i}(C, T)", "T <= 0"], note="§704.5f")
        p.rule(f"dies_{i}(C)", [f"present_{i}(C)", f"toughness_{i}(C, T)", "T > 0", "marked(C, D)", "D >= T"], note="§704.5g")
        # frame axiom: a creature that didn't die carries to the next round (staged -> stratified).
        if i < MAX:
            p.decl(f"present_{i + 1}", [("c", "symbol")])
            p.rule(f"present_{i + 1}(C)", [f"present_{i}(C)", f"!dies_{i}(C)"], note="§704.3 re-check after applying")
        p.blank()

    # aggregate across rounds.
    p.decl("dies_step", [("c", "symbol"), ("s", "number")])
    for i in range(MAX + 1):
        p.rule(f"dies_step(C, {i})", [f"dies_{i}(C)"])
    p.decl("dead", [("c", "symbol")])
    p.rule("dead(C)", ["dies_step(C, _)"])
    p.blank()
    p.output("dies_step", "dead")
    p.blank()
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()
    p.comment("scenario under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/sba_demo.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/sba_demo.dl")


if __name__ == "__main__":
    main()
