"""Build datalog/rules_index.dl — a deterministic index of EVERY rule/subrule in
rules.txt as Datalog facts. This is the base scaffold for the game engine: every
rule/subrule unit is addressable, so coverage toward 100% is measurable and
queryable. Pure structure parsed from rules.txt (no hand-authored game logic).

  section(num, title)          - the 9 sections
  rule_group(num, sec, title)  - the ~147 groups (e.g. 702)
  rule_unit(number, group, kind) - every rule + subrule, kind = "rule" | "subrule"
  has_example(number)          - units carrying an Example: block
"""

from __future__ import annotations

from pathlib import Path

from dlgen import Program
from rules_parser import split


def _q(s: str) -> str:
    return s.replace('"', "'").strip()


def build() -> tuple[str, dict]:
    doc = split(Path("rules.txt").read_text(encoding="utf-8"))
    p = Program()
    p.comment("rules_index.dl — GENERATED by build_rules_index.py. Deterministic index of")
    p.comment("every rule/subrule in rules.txt (the engine scaffold + the 100%-coverage denominator).")
    p.blank()
    p.decl("section", [("num", "symbol"), ("title", "symbol")])
    p.decl("rule_group", [("num", "symbol"), ("sec", "symbol"), ("title", "symbol")])
    p.decl("rule_unit", [("number", "symbol"), ("grp", "symbol"), ("kind", "symbol")])
    p.decl("has_example", [("number", "symbol")])
    p.blank()

    n_groups = n_rules = n_sub = n_ex = 0
    for s in doc.sections:
        p.fact(f'section("{s.number}", "{_q(s.title)}")')
        for g in s.groups:
            p.fact(f'rule_group("{g.number}", "{s.number}", "{_q(g.title)}")')
            n_groups += 1
            for r in g.rules:
                p.fact(f'rule_unit("{r.number}", "{g.number}", "rule")')
                n_rules += 1
                if r.examples:
                    p.fact(f'has_example("{r.number}")'); n_ex += 1
                for sr in r.subrules:
                    p.fact(f'rule_unit("{sr.number}", "{g.number}", "subrule")')
                    n_sub += 1
                    if sr.examples:
                        p.fact(f'has_example("{sr.number}")'); n_ex += 1
    p.blank()
    p.comment("derived totals (queryable)")
    p.decl("n_units", [("n", "number")])
    p.rule("n_units(N)", ["N = count : { rule_unit(_, _, _) }"])
    p.output("n_units")
    return p.text(), {"sections": len(doc.sections), "groups": n_groups,
                      "rules": n_rules, "subrules": n_sub, "units": n_rules + n_sub, "examples": n_ex}


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    source, report = build()
    Path("datalog/rules_index.dl").write_text(source, encoding="utf-8")
    print("wrote datalog/rules_index.dl")
    print(f"  {report['sections']} sections, {report['groups']} groups, "
          f"{report['units']} units ({report['rules']} rules + {report['subrules']} subrules), "
          f"{report['examples']} with examples")


if __name__ == "__main__":
    main()
