"""cedh_decklists.py — recent (2026) cEDH tournament/top-deck lists, gathered from Moxfield
via the public deck API (api2.moxfield.com/v3/decks/all/<id>), for the witchcraft card-target
analysis. cEDH is 100-card singleton Commander, so every count is 1 except basic lands.

Each deck: {commander:[...], archetype, source (Moxfield URL), date (lastUpdated), cards:{name:count}}.
Card names are EXACT oracle names as Moxfield serves them; verified against mtgjson/oracle_corpus.json
in target_analysis_cedh.py (ABSENT cards are flagged there, not silently dropped).
"""

DECKS = {
    'Blue Farm': {
        "commander": ['Tymna the Weaver', "Kraum, Ludevic's Opus"],
        "archetype": 'Turbo / Midrange',
        "source": 'https://moxfield.com/decks/7O1sCuIti0igU6Us_Jhadg',
        "date": '2026-06-07',
        "cards": {
            'Ad Nauseam': 1,
            "An Offer You Can't Refuse": 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Arid Mesa': 1,
            'Badlands': 1,
            'Beseech the Mirror': 1,
            'Birgi, God of Storytelling // Harnfel, Horn of Bounty': 1,
            'Bloodstained Mire': 1,
            'Borne Upon a Wind': 1,
            'Brain Freeze': 1,
            'Cabal Ritual': 1,
            'Cavern of Souls': 1,
            'Chain of Vapor': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'Command Tower': 1,
            'Culling the Weak': 1,
            'Dark Ritual': 1,
            'Deflecting Swat': 1,
            'Demonic Consultation': 1,
            'Demonic Tutor': 1,
            'Diabolic Intent': 1,
            "Dragon's Rage Channeler": 1,
            'Enlightened Tutor': 1,
            'Esper Sentinel': 1,
            'Exotic Orchard': 1,
            'Fellwar Stone': 1,
            'Fierce Guardianship': 1,
            'Final Fortune': 1,
            'Flare of Duplication': 1,
            'Flashback': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Force of Negation': 1,
            'Force of Will': 1,
            'Gamble': 1,
            'Gemstone Caverns': 1,
            'Grand Abolisher': 1,
            'Hexing Squelcher': 1,
            'Imperial Seal': 1,
            'Into the Flood Maw': 1,
            'Intuition': 1,
            "Jeska's Will": 1,
            'Knuckles the Echidna': 1,
            'Last Chance': 1,
            "Lion's Eye Diamond": 1,
            'Lotho, Corrupt Shirriff': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Mana Vault': 1,
            'Marsh Flats': 1,
            'Mental Misstep': 1,
            'Misty Rainforest': 1,
            'Mnemonic Betrayal': 1,
            'Mockingbird': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            'Mystic Remora': 1,
            'Mystical Tutor': 1,
            'Necropotence': 1,
            'Otawara, Soaring City': 1,
            'Pact of Negation': 1,
            'Plateau': 1,
            'Polluted Delta': 1,
            'Ragavan, Nimble Pilferer': 1,
            'Rain of Filth': 1,
            'Ranger-Captain of Eos': 1,
            'Red Elemental Blast': 1,
            'Rhystic Study': 1,
            'Rite of Flame': 1,
            'Rograkh, Son of Rohgahh': 1,
            'Scalding Tarn': 1,
            'Scrubland': 1,
            "Sevinne's Reclamation": 1,
            'Silence': 1,
            'Simian Spirit Guide': 1,
            'Smothering Tithe': 1,
            'Snapback': 1,
            'Sol Ring': 1,
            'Spire of Industry': 1,
            'Swan Song': 1,
            'Tainted Pact': 1,
            'Tarnished Citadel': 1,
            'Tataru Taru': 1,
            "Thassa's Oracle": 1,
            'Tundra': 1,
            'Underground Sea': 1,
            'Underworld Breach': 1,
            'Valley Floodcaller': 1,
            'Vampiric Tutor': 1,
            'Verdant Catacombs': 1,
            'Voice of Victory': 1,
            'Volcanic Island': 1,
            'Wheel of Fortune': 1,
            'Windswept Heath': 1,
            'Wishclaw Talisman': 1,
        },
    },
    'Rog/Thras Turbo Digging': {
        "commander": ['Rograkh, Son of Rohgahh', 'Thrasios, Triton Hero'],
        "archetype": 'Turbo / Combo',
        "source": 'https://moxfield.com/decks/Uhhiyn7Aq0CbmATRi3VLwQ',
        "date": '2026-05-08',
        "cards": {
            'Ancient Tomb': 1,
            'Badgermole Cub': 1,
            "Biomancer's Familiar": 1,
            'Birds of Paradise': 1,
            'Boseiju, Who Endures': 1,
            'Brain Freeze': 1,
            'Breeding Pool': 1,
            'Candelabra of Tawnos': 1,
            'Chain of Vapor': 1,
            'Chatterstorm': 1,
            'Chord of Calling': 1,
            'Chrome Mox': 1,
            'Clever Impersonator': 1,
            'Cloud of Faeries': 1,
            'Command Tower': 1,
            'Commandeer': 1,
            'Crop Rotation': 1,
            'Cyclonic Rift': 1,
            'Deflecting Swat': 1,
            'Deserted Temple': 1,
            'Dryad Arbor': 1,
            'Earthcraft': 1,
            'Elvish Spirit Guide': 1,
            'Emergence Zone': 1,
            'Enduring Vitality': 1,
            'Eternal Witness': 1,
            'Expedition Map': 1,
            'Faerie Mastermind': 1,
            'Fierce Guardianship': 1,
            'Finale of Devastation': 1,
            'Flare of Denial': 1,
            'Flare of Duplication': 1,
            'Flash Photography': 1,
            'Flesh Duplicate': 1,
            'Flooded Grove': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Force of Negation': 1,
            'Force of Will': 1,
            'Forest': 1,
            'Formidable Speaker': 1,
            'Frantic Search': 1,
            "Gaea's Cradle": 1,
            'Gamble': 1,
            "Green Sun's Zenith": 1,
            'Heartwood Storyteller': 1,
            'Hedge Maze': 1,
            'Hexing Squelcher': 1,
            'Invasion of Ikoria // Zilortha, Apex of Ikoria': 1,
            'Island': 1,
            "Lion's Eye Diamond": 1,
            'Lotus Petal': 1,
            "Louisoix's Sacrifice": 1,
            'Mana Confluence': 1,
            'Mana Vault': 1,
            'Mental Misstep': 1,
            "Minamo, School at Water's Edge": 1,
            'Mindbreak Trap': 1,
            'Misdirection': 1,
            'Mistrise Village': 1,
            'Misty Rainforest': 1,
            'Mockingbird': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mystic Remora': 1,
            "Nature's Rhythm": 1,
            'Noxious Revival': 1,
            'Oboro Breezecaller': 1,
            'Omni-Changeling': 1,
            'Otawara, Soaring City': 1,
            'Pact of Negation': 1,
            'Phantasmal Image': 1,
            'Phyrexian Metamorph': 1,
            'Polluted Delta': 1,
            'Rhystic Study': 1,
            'Scalding Tarn': 1,
            'Shifting Woodland': 1,
            'Snap': 1,
            'Sol Ring': 1,
            'Sowing Mycospawn': 1,
            'Spellseeker': 1,
            'Springheart Nantuko': 1,
            'Springleaf Drum': 1,
            "Summoner's Pact": 1,
            'Swan Song': 1,
            'Taiga': 1,
            'Talon Gates of Madara': 1,
            'The Cabbage Merchant': 1,
            "This Town Ain't Big Enough": 1,
            'Tropical Island': 1,
            'Underworld Breach': 1,
            'Valley Floodcaller': 1,
            'Veil of Summer': 1,
            'Verdant Catacombs': 1,
            'Volcanic Island': 1,
            'Wild Growth': 1,
            'Windswept Heath': 1,
            'Wooded Foothills': 1,
        },
    },
    'Tevesh/Thrasios Midrange': {
        "commander": ['Tevesh Szat, Doom of Fools', 'Thrasios, Triton Hero'],
        "archetype": 'Midrange / Control',
        "source": 'https://moxfield.com/decks/9RfXdx4TuUqc3Yz306EFsg',
        "date": '2026-03-16',
        "cards": {
            'Ad Nauseam': 1,
            "An Offer You Can't Refuse": 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Aura Thief': 1,
            'Basalt Monolith': 1,
            'Bayou': 1,
            'Beseech the Mirror': 1,
            'Bloodstained Mire': 1,
            "Bolas's Citadel": 1,
            'Boseiju, Who Endures': 1,
            'Braids, Arisen Nightmare': 1,
            'Breeding Pool': 1,
            'Cabal Pit': 1,
            'Cabal Ritual': 1,
            'Carpet of Flowers': 1,
            'Chain of Vapor': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'Command Tower': 1,
            'Culling Ritual': 1,
            'Culling the Weak': 1,
            'Cyclonic Rift': 1,
            'Dark Ritual': 1,
            'Deadly Rollick': 1,
            'Delighted Halfling': 1,
            'Demonic Consultation': 1,
            'Demonic Tutor': 1,
            'Diabolic Intent': 1,
            'Dosan the Falling Leaf': 1,
            'Elvish Spirit Guide': 1,
            'Exotic Orchard': 1,
            'Fellwar Stone': 1,
            'Fierce Guardianship': 1,
            'Flare of Denial': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Forbidden Orchard': 1,
            'Force of Negation': 1,
            'Force of Will': 1,
            'Gemstone Caverns': 1,
            'Grim Monolith': 1,
            'Imperial Seal': 1,
            'Kinnan, Bonder Prodigy': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Mana Vault': 1,
            'Marsh Flats': 1,
            'Mental Misstep': 1,
            "Minamo, School at Water's Edge": 1,
            'Mindbreak Trap': 1,
            'Mirrormade': 1,
            'Misdirection': 1,
            'Misty Rainforest': 1,
            'Mnemonic Betrayal': 1,
            'Morphic Pool': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mystic Remora': 1,
            'Necropotence': 1,
            'Nurturing Peatland': 1,
            'Opposition Agent': 1,
            'Orcish Bowmasters': 1,
            'Overgrown Tomb': 1,
            'Polluted Delta': 1,
            'Power Artifact': 1,
            "Praetor's Grasp": 1,
            'Rejuvenating Springs': 1,
            'Rhystic Study': 1,
            'Scalding Tarn': 1,
            'Skullclamp': 1,
            'Snapback': 1,
            'Sol Ring': 1,
            'Spire of Industry': 1,
            'Staff of Compleation': 1,
            'Starting Town': 1,
            'Submerge': 1,
            'Subtlety': 1,
            'Swan Song': 1,
            'Tainted Pact': 1,
            'Talion, the Kindly Lord': 1,
            'Talisman of Dominance': 1,
            "Thassa's Oracle": 1,
            'The One Ring': 1,
            'Toxic Deluge': 1,
            'Tropical Island': 1,
            'Underground Sea': 1,
            'Undergrowth Stadium': 1,
            'Vampiric Tutor': 1,
            'Veil of Summer': 1,
            'Verdant Catacombs': 1,
            'Wan Shi Tong, Librarian': 1,
            'Watery Grave': 1,
            'Wild Growth': 1,
            'Windswept Heath': 1,
            'Wishclaw Talisman': 1,
            'Wooded Foothills': 1,
            'Yawgmoth, Thran Physician': 1,
        },
    },
    'Kinnan, Bonder Prodigy': {
        "commander": ['Kinnan, Bonder Prodigy'],
        "archetype": 'Mono-color Combo / Ramp',
        "source": 'https://moxfield.com/decks/jfQkmstWTU-ucVSKHmqnEQ',
        "date": '2026-03-10',
        "cards": {
            "An Offer You Can't Refuse": 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Barkchannel Pathway // Tidechannel Pathway': 1,
            'Basalt Monolith': 1,
            'Birds of Paradise': 1,
            'Boseiju, Who Endures': 1,
            'Breeding Pool': 1,
            'Cephalid Coliseum': 1,
            'Chord of Calling': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'Clever Impersonator': 1,
            'Command Tower': 1,
            'Commandeer': 1,
            'Consecrated Sphinx': 1,
            'Copy Artifact': 1,
            'Copy Enchantment': 1,
            'Delighted Halfling': 1,
            'Disrupting Shoal': 1,
            'Dramatic Reversal': 1,
            'Drift of Phantasms': 1,
            'Elvish Mystic': 1,
            'Elvish Spirit Guide': 1,
            'Endurance': 1,
            'Enduring Vitality': 1,
            'Faerie Mastermind': 1,
            'Fellwar Stone': 1,
            'Fierce Guardianship': 1,
            'Finale of Devastation': 1,
            'Flash Photography': 1,
            'Flesh Duplicate': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Force of Negation': 1,
            'Force of Will': 1,
            'Forest': 1,
            'Fyndhorn Elves': 1,
            'Gemstone Caverns': 1,
            "Green Sun's Zenith": 1,
            'Grim Monolith': 1,
            'Hidden Strings': 1,
            'High Fae Trickster': 1,
            'Hullbreaker Horror': 1,
            'Hydroelectric Specimen // Hydroelectric Laboratory': 1,
            'Imposter Mech': 1,
            'Into the Flood Maw': 1,
            'Invasion of Ikoria // Zilortha, Apex of Ikoria': 1,
            'Island': 1,
            'Llanowar Elves': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Mana Vault': 1,
            'Mental Misstep': 1,
            'Mindbreak Trap': 1,
            'Mirage Mirror': 1,
            'Mirrormade': 1,
            'Misdirection': 1,
            'Misty Rainforest': 1,
            'Mockingbird': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            'Mystic Remora': 1,
            "Nature's Rhythm": 1,
            'Nezahal, Primal Tide': 1,
            'Nyxbloom Ancient': 1,
            'Otawara, Soaring City': 1,
            'Pact of Negation': 1,
            'Phyrexian Metamorph': 1,
            'Polluted Delta': 1,
            'Rejuvenating Springs': 1,
            'Rhystic Study': 1,
            'Scalding Tarn': 1,
            'Seedborn Muse': 1,
            'Simic Signet': 1,
            'Sink into Stupor // Soporific Springs': 1,
            'Snapback': 1,
            'Sol Ring': 1,
            'Springleaf Drum': 1,
            'Swan Song': 1,
            'Talisman of Curiosity': 1,
            'Tarnished Citadel': 1,
            'The Cabbage Merchant': 1,
            'The Unagi of Kyoshi Island': 1,
            'Thrasios, Triton Hero': 1,
            'Transmute Artifact': 1,
            'Trophy Mage': 1,
            'Tropical Island': 1,
            'Valley Floodcaller': 1,
            'Veil of Summer': 1,
            'Verdant Catacombs': 1,
            'Wan Shi Tong, Librarian': 1,
            'Waterlogged Grove': 1,
            'Whir of Invention': 1,
            'Windswept Heath': 1,
            'Wooded Foothills': 1,
            'Worldly Tutor': 1,
            'Yavimaya Coast': 1,
        },
    },
    'Sisay, Weatherlight Captain': {
        "commander": ['Sisay, Weatherlight Captain'],
        "archetype": 'Toolbox / Planeswalker combo',
        "source": 'https://moxfield.com/decks/c573mrxHWEiBjgwSabxDSA',
        "date": '2026-04-17',
        "cards": {
            'Abigale, Eloquent First-Year': 1,
            "Agatha's Soul Cauldron": 1,
            "An Offer You Can't Refuse": 1,
            'Anafenza, the Foremost': 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Arid Mesa': 1,
            "Avacyn's Pilgrim": 1,
            'Badlands': 1,
            'Bayou': 1,
            'Birds of Paradise': 1,
            'Bloodstained Mire': 1,
            'Bloom Tender': 1,
            'Boseiju, Who Endures': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'Command Tower': 1,
            'Deadpool, Trading Card': 1,
            'Deathrite Shaman': 1,
            'Deflecting Swat': 1,
            'Delighted Halfling': 1,
            'Demonic Tutor': 1,
            'Derevi, Empyrial Tactician': 1,
            'Dihada, Binder of Wills': 1,
            'Drana and Linvala': 1,
            'Elesh Norn, Grand Cenobite': 1,
            'Elesh Norn, Mother of Machines': 1,
            'Elves of Deep Shadow': 1,
            'Emiel the Blessed': 1,
            'Enduring Vitality': 1,
            'Ertai Resurrected': 1,
            'Exotic Orchard': 1,
            'Faeburrow Elder': 1,
            'Fellwar Stone': 1,
            'Fierce Guardianship': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Force of Will': 1,
            'Formidable Speaker': 1,
            "Gaea's Cradle": 1,
            'Grim Hireling': 1,
            'Ignoble Hierarch': 1,
            'Ioreth of the Healing House': 1,
            'Kambal, Profiteering Mayor': 1,
            'Katilda, Dawnhart Prime': 1,
            'Kinnan, Bonder Prodigy': 1,
            'Kutzil, Malamet Exemplar': 1,
            'Lotho, Corrupt Shirriff': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Marsh Flats': 1,
            'Marvin, Murderous Mimic': 1,
            'Mental Misstep': 1,
            "Minamo, School at Water's Edge": 1,
            'Mindbreak Trap': 1,
            'Misty Rainforest': 1,
            'Mount Doom': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mystic Remora': 1,
            'Noble Hierarch': 1,
            'Orcish Bowmasters': 1,
            'Otawara, Soaring City': 1,
            'Plateau': 1,
            'Polluted Delta': 1,
            'Professional Face-Breaker': 1,
            'Ragavan, Nimble Pilferer': 1,
            'Relic of Legends': 1,
            'Rhystic Study': 1,
            'Ruby, Daring Tracker': 1,
            'Sakashima the Impostor': 1,
            'Savannah': 1,
            'Scalding Tarn': 1,
            'Scrubland': 1,
            'Selvala, Heart of the Wilds': 1,
            'Sigarda, Font of Blessings': 1,
            'Silence': 1,
            'Smothering Tithe': 1,
            'Sol Ring': 1,
            'Spell Pierce': 1,
            'Swords to Plowshares': 1,
            'Taiga': 1,
            'Talisman of Unity': 1,
            'Tam, Mindful First-Year': 1,
            'Tamiyo, Inquisitive Student // Tamiyo, Seasoned Scholar': 1,
            'Teferi, Time Raveler': 1,
            'The One Ring': 1,
            'Torgal, A Fine Hound': 1,
            'Tropical Island': 1,
            'Tundra': 1,
            'Tyvar, Jubilant Brawler': 1,
            'Underground Sea': 1,
            'Vampiric Tutor': 1,
            'Verdant Catacombs': 1,
            'Voice of Victory': 1,
            'Volcanic Island': 1,
            'Wan Shi Tong, Librarian': 1,
            'Windswept Heath': 1,
            'Wooded Foothills': 1,
        },
    },
    'Etali Food Chain': {
        "commander": ['Etali, Primal Conqueror // Etali, Primal Sickness'],
        "archetype": 'Food Chain / Combo',
        "source": 'https://moxfield.com/decks/6GjkcWlSskSHFVknnUQ7lQ',
        "date": '2026-02-10',
        "cards": {
            'Abrade': 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Arid Mesa': 1,
            "Autumn's Veil": 1,
            'Birds of Paradise': 1,
            'Birgi, God of Storytelling // Harnfel, Horn of Bounty': 1,
            'Bloodstained Mire': 1,
            'Boseiju, Who Endures': 1,
            'Carpet of Flowers': 1,
            'Cavern of Souls': 1,
            'Chord of Calling': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'City of Traitors': 1,
            'Command Tower': 1,
            'Crop Rotation': 1,
            'Cursed Mirror': 1,
            'Defense Grid': 1,
            'Deflecting Swat': 1,
            'Delighted Halfling': 1,
            'Desperate Ritual': 1,
            'Disciple of Freyalise // Garden of Freyalise': 1,
            'Dualcaster Mage': 1,
            'Eldritch Evolution': 1,
            'Electroduplicate': 1,
            'Elvish Spirit Guide': 1,
            'Eternal Witness': 1,
            'Fellwar Stone': 1,
            'Finale of Devastation': 1,
            'Flare of Duplication': 1,
            'Food Chain': 1,
            'Force of Vigor': 1,
            'Fury': 1,
            "Gaea's Cradle": 1,
            'Gamble': 1,
            'Gemstone Caverns': 1,
            'Geosurge': 1,
            'Glimpse the Impossible': 1,
            "Green Sun's Zenith": 1,
            'Grim Monolith': 1,
            'Grove of the Burnwillows': 1,
            'Heat Shimmer': 1,
            'Hellkite Courser': 1,
            'Hexing Squelcher': 1,
            'Hunting Velociraptor': 1,
            'Infernal Plunge': 1,
            'Invasion of Ikoria // Zilortha, Apex of Ikoria': 1,
            'Jaxis, the Troublemaker': 1,
            "Jeska's Will": 1,
            'Karplusan Forest': 1,
            'Lightning Bolt': 1,
            "Lion's Eye Diamond": 1,
            'Llanowar Elves': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Mana Vault': 1,
            'Metamorphosis': 1,
            'Misty Rainforest': 1,
            'Molten Duplication': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            "Nature's Rhythm": 1,
            'Noxious Revival': 1,
            'Orcish Lumberjack': 1,
            'Prismatic Vista': 1,
            'Pyretic Ritual': 1,
            'Pyroblast': 1,
            'Ragavan, Nimble Pilferer': 1,
            'Red Elemental Blast': 1,
            'Rionya, Fire Dancer': 1,
            'Rite of Flame': 1,
            'Scalding Tarn': 1,
            'Seething Song': 1,
            'Shatterskull Smashing // Shatterskull, the Hammer Pass': 1,
            'Simian Spirit Guide': 1,
            'Snow-Covered Forest': 1,
            'Snow-Covered Mountain': 1,
            'Sol Ring': 1,
            'Spire Garden': 1,
            'Squee, the Immortal': 1,
            'Starting Town': 1,
            'Stomping Ground': 1,
            'Taiga': 1,
            'Talisman of Impulse': 1,
            'Tinder Wall': 1,
            'Treasonous Ogre': 1,
            'Twinflame': 1,
            'Underworld Breach': 1,
            "Urza's Saga": 1,
            'Utopia Sprawl': 1,
            'Veil of Summer': 1,
            'Verdant Catacombs': 1,
            'Wheel of Fortune': 1,
            'Wild Growth': 1,
            'Windswept Heath': 1,
            'Wooded Foothills': 1,
            'Worldly Tutor': 1,
            '________ Goblin': 1,
        },
    },
    'Atraxa, Grand Unifier Food Chain': {
        "commander": ['Atraxa, Grand Unifier'],
        "archetype": 'Food Chain / Combo',
        "source": 'https://moxfield.com/decks/Hn9VtfRNRUuZO7zT5ujWMA',
        "date": '2026-01-31',
        "cards": {
            'Abrupt Decay': 1,
            "An Offer You Can't Refuse": 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Archivist of Oghma': 1,
            "Assassin's Trophy": 1,
            'Bayou': 1,
            'Birds of Paradise': 1,
            'Bloodstained Mire': 1,
            'Boseiju, Who Endures': 1,
            'Bountiful Promenade': 1,
            'Breeding Pool': 1,
            'Carpet of Flowers': 1,
            'Cavern of Souls': 1,
            'Chain of Vapor': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'Command Tower': 1,
            'Crop Rotation': 1,
            'Culling Ritual': 1,
            'Cyclonic Rift': 1,
            'Dark Ritual': 1,
            'Dauthi Voidwalker': 1,
            'Deathrite Shaman': 1,
            'Demonic Consultation': 1,
            'Demonic Tutor': 1,
            'Dispel': 1,
            'Displacer Kitten': 1,
            'Drannith Magistrate': 1,
            'Eldritch Evolution': 1,
            'Elvish Spirit Guide': 1,
            'Emiel the Blessed': 1,
            'Enlightened Tutor': 1,
            'Esper Sentinel': 1,
            'Eternal Scourge': 1,
            'Exotic Orchard': 1,
            'Faerie Mastermind': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Food Chain': 1,
            'Forbidden Orchard': 1,
            'Force of Negation': 1,
            'Force of Will': 1,
            'Forest': 1,
            "Gaea's Cradle": 1,
            'Gemstone Caverns': 1,
            'Grand Abolisher': 1,
            'Imperial Seal': 1,
            'Imposter Mech': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Mana Drain': 1,
            'Mana Vault': 1,
            'Marsh Flats': 1,
            'Mental Misstep': 1,
            'Mindbreak Trap': 1,
            'Misty Rainforest': 1,
            'Mnemonic Betrayal': 1,
            'Morphic Pool': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            'Mystic Remora': 1,
            'Noble Hierarch': 1,
            'Notion Thief': 1,
            'Noxious Revival': 1,
            'Opposition Agent': 1,
            'Orcish Bowmasters': 1,
            'Otawara, Soaring City': 1,
            'Pact of Negation': 1,
            'Phyrexian Metamorph': 1,
            'Polluted Delta': 1,
            'Ranger-Captain of Eos': 1,
            'Reanimate': 1,
            'Rhystic Study': 1,
            'Savannah': 1,
            'Scalding Tarn': 1,
            'Scrubland': 1,
            'Sea of Clouds': 1,
            'Silence': 1,
            'Smothering Tithe': 1,
            'Sol Ring': 1,
            'Swan Song': 1,
            'Swords to Plowshares': 1,
            'Tainted Pact': 1,
            'Teferi, Time Raveler': 1,
            "Thassa's Oracle": 1,
            'Timetwister': 1,
            'Tropical Island': 1,
            'Tundra': 1,
            'Underground Sea': 1,
            'Vampiric Tutor': 1,
            'Veil of Summer': 1,
            'Verdant Catacombs': 1,
            'Walking Ballista': 1,
            'Wandering Archaic // Explore the Vastlands': 1,
            'Windfall': 1,
            'Windswept Heath': 1,
            'Wishclaw Talisman': 1,
            'Wooded Foothills': 1,
        },
    },
    'Tivit Time Sieve Midrange': {
        "commander": ['Tivit, Seller of Secrets'],
        "archetype": 'Stax / Control / Combo',
        "source": 'https://moxfield.com/decks/_7iACzJAqEW2P1xTZjqEyQ',
        "date": '2026-04-10',
        "cards": {
            'Amphibian Downpour': 1,
            "An Offer You Can't Refuse": 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Arid Mesa': 1,
            'Bloodstained Mire': 1,
            'Cavern of Souls': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'Command Tower': 1,
            'Commandeer': 1,
            'Cyclonic Rift': 1,
            'Dark Ritual': 1,
            'Demonic Consultation': 1,
            'Demonic Tutor': 1,
            'Displacer Kitten': 1,
            'Drannith Magistrate': 1,
            'Enlightened Tutor': 1,
            'Esper Sentinel': 1,
            'Exotic Orchard': 1,
            'Faerie Mastermind': 1,
            'Fellwar Stone': 1,
            'Fierce Guardianship': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Force of Negation': 1,
            'Force of Will': 1,
            'Gemstone Caverns': 1,
            'Gifts Ungiven': 1,
            'Godless Shrine': 1,
            "Grafdigger's Cage": 1,
            'Grand Abolisher': 1,
            'Grim Monolith': 1,
            'Hallowed Fountain': 1,
            'Imperial Seal': 1,
            "Lim-Dûl's Vault": 1,
            'Lotho, Corrupt Shirriff': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Mana Drain': 1,
            'Mana Vault': 1,
            'Marsh Flats': 1,
            'Mental Misstep': 1,
            "Minamo, School at Water's Edge": 1,
            'Mindbreak Trap': 1,
            'Misdirection': 1,
            'Misty Rainforest': 1,
            'Mockingbird': 1,
            'Morphic Pool': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            'Muddle the Mixture': 1,
            'Mystic Remora': 1,
            'Mystical Tutor': 1,
            'Opposition Agent': 1,
            'Orcish Bowmasters': 1,
            'Otawara, Soaring City': 1,
            'Pact of Negation': 1,
            'Phyrexian Metamorph': 1,
            'Polluted Delta': 1,
            'Ranger-Captain of Eos': 1,
            'Reanimate': 1,
            'Retraction Helix': 1,
            'Rhystic Study': 1,
            'Scalding Tarn': 1,
            'Scrubland': 1,
            'Sea of Clouds': 1,
            "Sevinne's Reclamation": 1,
            'Silence': 1,
            'Smothering Tithe': 1,
            'Snapcaster Mage': 1,
            'Sol Ring': 1,
            'Spire of Industry': 1,
            'Strix Serenade': 1,
            'Swan Song': 1,
            'Swords to Plowshares': 1,
            'Tainted Pact': 1,
            'Talisman of Dominance': 1,
            'Tataru Taru': 1,
            'Teferi, Time Raveler': 1,
            'Tezzeret, Cruel Captain': 1,
            "Thassa's Oracle": 1,
            'The One Ring': 1,
            'Time Sieve': 1,
            'Toxic Deluge': 1,
            'Transmute Artifact': 1,
            'Tundra': 1,
            'Underground Sea': 1,
            "Urza's Saga": 1,
            'Urza, Lord High Artificer': 1,
            'Valley Floodcaller': 1,
            'Vampiric Tutor': 1,
            'Verdant Catacombs': 1,
            'Vexing Bauble': 1,
            'Voice of Victory': 1,
            'Wan Shi Tong, Librarian': 1,
            'Watery Grave': 1,
            'Windswept Heath': 1,
            'Wishclaw Talisman': 1,
        },
    },
    'Magda Brazen Outlaw (Magdanomicon)': {
        "commander": ['Magda, Brazen Outlaw'],
        "archetype": 'Stax / Treasure combo',
        "source": 'https://moxfield.com/decks/8Y4qOAcLN0O_HHYhOboV3Q',
        "date": '2026-05-20',
        "cards": {
            'Abrade': 1,
            'Adaptive Automaton': 1,
            'Ancient Tomb': 1,
            'Axgard Cavalry': 1,
            'Barbarian Ring': 1,
            'Barkform Harvester': 1,
            'Battered Golem': 1,
            'Bloodfire Dwarf': 1,
            'Bottle-Cap Blast': 1,
            'Cavern of Souls': 1,
            'Chaos Warp': 1,
            'Chrome Mox': 1,
            'City of Traitors': 1,
            'Clock of Omens': 1,
            'Clown Car': 1,
            'Command Beacon': 1,
            'Damping Sphere': 1,
            'Dead // Gone': 1,
            'Deflecting Swat': 1,
            'Disruptor Flute': 1,
            'Dwarven Armorer': 1,
            'Dwarven Bloodboiler': 1,
            'Dwarven Grunt': 1,
            'Dwarven Scorcher': 1,
            'Dwarven Trader': 1,
            'Enslaved Dwarf': 1,
            'Firdoch Core': 1,
            'Flywheel Racer': 1,
            'Galvanic Blast': 1,
            'Gemstone Caverns': 1,
            'Gogo, Mysterious Mime': 1,
            "Grafdigger's Cage": 1,
            'Great Furnace': 1,
            'Hammerheim': 1,
            'Holdout Settlement': 1,
            "Jeska's Will": 1,
            'Kavaron, Memorial World': 1,
            'Knuckles the Echidna': 1,
            'Legion Extruder': 1,
            'Liberated Dwarf': 1,
            'Lifecraft Engine': 1,
            'Lightning Bolt': 1,
            'Liquimetal Torque': 1,
            'Lotus Petal': 1,
            'Magda, the Hoardmaster': 1,
            'Mana Vault': 1,
            'Maskwood Nexus': 1,
            'Metallic Mimic': 1,
            'Mountain': 7,
            'Mox Opal': 1,
            'Mutavault': 1,
            "Peter Parker's Camera": 1,
            'Pinnacle Monk // Mystic Peak': 1,
            'Pithing Needle': 1,
            'Plundering Barbarian': 1,
            'Portal to Phyrexia': 1,
            'Professional Face-Breaker': 1,
            'Pyroblast': 1,
            'Pyrokinesis': 1,
            'Red Elemental Blast': 1,
            'Redirect Lightning': 1,
            'Relic of Legends': 1,
            'Return the Favor': 1,
            'Roaming Throne': 1,
            'Sculpting Steel': 1,
            'Shatterskull Smashing // Shatterskull, the Hammer Pass': 1,
            'Shinka, the Bloodsoaked Keep': 1,
            'Simian Spirit Guide': 1,
            "Smuggler's Copter": 1,
            'Sokenzan, Crucible of Defiance': 1,
            'Sol Ring': 1,
            'Spark Mage': 1,
            'Springleaf Drum': 1,
            'Stalactite Dagger': 1,
            'Sudden Shock': 1,
            'Sundering Eruption // Volcanic Fissure': 1,
            "Survivors' Encampment": 1,
            'Talon Gates of Madara': 1,
            'Tezzeret, Cruel Captain': 1,
            'The One Ring': 1,
            'Three Tree Mascot': 1,
            "Tibalt's Trickery": 1,
            'Torpor Orb': 1,
            'Treasure Vault': 1,
            'Twinshot Sniper': 1,
            'Universal Automaton': 1,
            'Unlicensed Hearse': 1,
            'Untimely Malfunction': 1,
            "Urza's Saga": 1,
            'Vexing Bauble': 1,
            'Volatile Fault': 1,
            'Xorn': 1,
            "Zoyowa's Justice": 1,
        },
    },
    'Ral Turbo Storm': {
        "commander": ['Ral, Monsoon Mage // Ral, Leyline Prodigy'],
        "archetype": 'Storm / Turbo',
        "source": 'https://moxfield.com/decks/5LIEqQbIJ0SesdDd4XCTPw',
        "date": '2026-01-31',
        "cards": {
            'Abandon Attachments': 1,
            "An Offer You Can't Refuse": 1,
            'Ancient Tomb': 1,
            'Arid Mesa': 1,
            'Birgi, God of Storytelling // Harnfel, Horn of Bounty': 1,
            'Bloodstained Mire': 1,
            'Bonus Round': 1,
            'Brain Freeze': 1,
            'Chain of Vapor': 1,
            'Chrome Mox': 1,
            'Command Tower': 1,
            'Daze': 1,
            'Deflecting Swat': 1,
            'Demand Answers': 1,
            'Desperate Ritual': 1,
            'Echo of Eons': 1,
            'Faithless Looting': 1,
            'Fierce Guardianship': 1,
            'Flare of Duplication': 1,
            'Flooded Strand': 1,
            'Frantic Search': 1,
            'Gamble': 1,
            'Gemstone Caverns': 1,
            'Gitaxian Probe': 1,
            'Glimpse the Impossible': 1,
            'Grapeshot': 1,
            'Great Furnace': 1,
            'Gut Shot': 1,
            'Hexing Squelcher': 1,
            'Highway Robbery': 1,
            'Intuition': 1,
            'Invoke Calamity': 1,
            "Jeska's Will": 1,
            "Kari Zev's Expertise": 1,
            'Lava Dart': 1,
            'Lightning Bolt': 1,
            "Lion's Eye Diamond": 1,
            'Lotus Petal': 1,
            'Mana Vault': 1,
            'Mental Misstep': 1,
            "Mind's Desire": 1,
            'Misty Rainforest': 1,
            'Mogg Salvage': 1,
            'Mountain': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            'Mystic Remora': 1,
            'Mystical Tutor': 1,
            'Opera Love Song': 1,
            'Overmaster': 1,
            'Pact of Negation': 1,
            'Past in Flames': 1,
            'Polluted Delta': 1,
            'Pyretic Ritual': 1,
            'Pyroblast': 1,
            'Quiet Speculation': 1,
            'Reckless Impulse': 1,
            'Recoup': 1,
            'Reiterate': 1,
            'Rite of Flame': 1,
            'Rob the Archives': 1,
            'Ruby Medallion': 1,
            'Runaway Steam-Kin': 1,
            'Scalding Tarn': 1,
            'Sea Gate Restoration // Sea Gate, Reborn': 1,
            'Seething Song': 1,
            'Shatterskull Smashing // Shatterskull, the Hammer Pass': 1,
            'Simian Spirit Guide': 1,
            'Sink into Stupor // Soporific Springs': 1,
            'Snap': 1,
            'Sol Ring': 1,
            "Sorceress's Schemes": 1,
            'Springleaf Drum': 1,
            'Steam Vents': 1,
            'Stock Up': 1,
            'Storm of Memories': 1,
            'Storm-Kiln Artist': 1,
            'Strike It Rich': 1,
            'Sundering Eruption // Volcanic Fissure': 1,
            'Tavern Scoundrel': 1,
            'Thundering Falls': 1,
            "Tibalt's Trickery": 1,
            'Timetwister': 1,
            'Treasonous Ogre': 1,
            'Twinferno': 1,
            'Underworld Breach': 1,
            'Valakut Awakening // Valakut Stoneforge': 1,
            'Vexing Bauble': 1,
            'Vivi Ornitier': 1,
            'Volcanic Island': 1,
            'Wheel of Fortune': 1,
            'Wheel of Misfortune': 1,
            'Will of the Jeskai': 1,
            'Windfall': 1,
            "Witch's Mark": 1,
            'Wooded Foothills': 1,
            "Wrenn's Resolve": 1,
            '________ Goblin': 1,
        },
    },
    'Stella Lee Wild Card': {
        "commander": ['Stella Lee, Wild Card'],
        "archetype": 'Spellslinger combo',
        "source": 'https://moxfield.com/decks/z3_k_aIXPEaP_uZw-XeJdw',
        "date": '2026-05-28',
        "cards": {
            "An Offer You Can't Refuse": 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Arena of Glory': 1,
            'Arid Mesa': 1,
            'Bloodstained Mire': 1,
            'Borne Upon a Wind': 1,
            'Brain Freeze': 1,
            'Brainstorm': 1,
            'Cephalid Coliseum': 1,
            'Cerulean Wisps': 1,
            'Chain Stasis': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'City of Traitors': 1,
            'Claim the Firstborn': 1,
            'Command Tower': 1,
            'Commandeer': 1,
            'Crimson Wisps': 1,
            'Deflecting Swat': 1,
            'Dramatic Reversal': 1,
            'Expedite': 1,
            'Faerie Mastermind': 1,
            'Fellwar Stone': 1,
            'Fierce Guardianship': 1,
            'Fiery Islet': 1,
            'Final Fortune': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Force of Negation': 1,
            'Force of Will': 1,
            'Frantic Search': 1,
            'Gamble': 1,
            'Gemstone Caverns': 1,
            'Gitaxian Probe': 1,
            'Gut Shot': 1,
            'Hidden Strings': 1,
            'Into the Flood Maw': 1,
            'Intuition': 1,
            'Island': 1,
            "Jeska's Will": 1,
            'Jeweled Amulet': 1,
            'Last Chance': 1,
            'Lightning Bolt': 1,
            "Lion's Eye Diamond": 1,
            'Lotus Petal': 1,
            'Magic Damper': 1,
            'Mana Confluence': 1,
            'Mana Vault': 1,
            'Mental Misstep': 1,
            'Merchant Scroll': 1,
            "Minamo, School at Water's Edge": 1,
            'Mindbreak Trap': 1,
            'Misdirection': 1,
            'Misty Rainforest': 1,
            'Mogg Salvage': 1,
            'Mountain': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            'Mystic Remora': 1,
            'Mystical Tutor': 1,
            'Otawara, Soaring City': 1,
            'Pact of Negation': 1,
            'Personal Tutor': 1,
            'Polluted Delta': 1,
            'Pyroblast': 1,
            'Ragavan, Nimble Pilferer': 1,
            'Red Elemental Blast': 1,
            'Refocus': 1,
            'Rhystic Study': 1,
            'Rite of Flame': 1,
            'Scalding Tarn': 1,
            'Sea Gate Restoration // Sea Gate, Reborn': 1,
            "Sensei's Divining Top": 1,
            'Shivan Reef': 1,
            'Shore Up': 1,
            'Simian Spirit Guide': 1,
            'Sink into Stupor // Soporific Springs': 1,
            'Snap': 1,
            'Sol Ring': 1,
            'Solve the Equation': 1,
            'Spellseeker': 1,
            'Steam Vents': 1,
            'Strike It Rich': 1,
            'Submerge': 1,
            'Swan Song': 1,
            'Talisman of Creativity': 1,
            'Teardrop Kami': 1,
            'The One Ring': 1,
            'Thundering Falls': 1,
            'Tidal Bore': 1,
            'Training Center': 1,
            'Twisted Fealty': 1,
            'Twitch': 1,
            'Underworld Breach': 1,
            'Valley Floodcaller': 1,
            'Volcanic Island': 1,
            'Wooded Foothills': 1,
        },
    },
    'Najeela Warrior Queen': {
        "commander": ['Najeela, the Blade-Blossom'],
        "archetype": 'Aggro / Combo',
        "source": 'https://moxfield.com/decks/jT8Y9X4tlUmeNZ2AjkD1Vg',
        "date": '2026-01-25',
        "cards": {
            'Ad Nauseam': 1,
            'Ancient Tomb': 1,
            'Arcane Signet': 1,
            'Arid Mesa': 1,
            'Badlands': 1,
            'Bayou': 1,
            'Birds of Paradise': 1,
            'Bloodstained Mire': 1,
            'Brain Freeze': 1,
            'Chain of Vapor': 1,
            'Chrome Mox': 1,
            'City of Brass': 1,
            'Command Tower': 1,
            'Culling Ritual': 1,
            'Culling the Weak': 1,
            'Dark Ritual': 1,
            'Deathrite Shaman': 1,
            'Deflecting Swat': 1,
            'Delighted Halfling': 1,
            'Demonic Consultation': 1,
            'Demonic Tutor': 1,
            'Derevi, Empyrial Tactician': 1,
            'Diabolic Intent': 1,
            "Eladamri's Call": 1,
            'Elvish Spirit Guide': 1,
            'Enlightened Tutor': 1,
            'Esper Sentinel': 1,
            'Exotic Orchard': 1,
            'Fellwar Stone': 1,
            'Fierce Guardianship': 1,
            'Final Fortune': 1,
            'Flooded Strand': 1,
            'Flusterstorm': 1,
            'Forbidden Orchard': 1,
            'Force of Will': 1,
            'Gamble': 1,
            'Gemstone Caverns': 1,
            'Gitaxian Probe': 1,
            "Green Sun's Zenith": 1,
            'Hexing Squelcher': 1,
            'Ignoble Hierarch': 1,
            'Imperial Seal': 1,
            'Intuition': 1,
            "Lion's Eye Diamond": 1,
            'Lotho, Corrupt Shirriff': 1,
            'Lotus Petal': 1,
            'Mana Confluence': 1,
            'Mana Vault': 1,
            'Marsh Flats': 1,
            'Mental Misstep': 1,
            'Mindbreak Trap': 1,
            'Misty Rainforest': 1,
            'Mockingbird': 1,
            'Mox Amber': 1,
            'Mox Diamond': 1,
            'Mox Opal': 1,
            'Mystic Remora': 1,
            'Mystical Tutor': 1,
            'Noble Hierarch': 1,
            'Pact of Negation': 1,
            'Plateau': 1,
            'Polluted Delta': 1,
            'Ragavan, Nimble Pilferer': 1,
            'Ranger-Captain of Eos': 1,
            'Red Elemental Blast': 1,
            'Rhystic Study': 1,
            'Rite of Flame': 1,
            'Samut, Vizier of Naktamun': 1,
            'Scalding Tarn': 1,
            'Scrubland': 1,
            "Sevinne's Reclamation": 1,
            'Silence': 1,
            'Simian Spirit Guide': 1,
            'Smothering Tithe': 1,
            'Sol Ring': 1,
            'Starting Town': 1,
            "Summoner's Pact": 1,
            'Swan Song': 1,
            'Swords to Plowshares': 1,
            'Taiga': 1,
            'Tainted Pact': 1,
            'Tarnished Citadel': 1,
            "Thassa's Oracle": 1,
            'The Cabbage Merchant': 1,
            'Tinder Wall': 1,
            'Tropical Island': 1,
            'Tundra': 1,
            'Underground Sea': 1,
            'Underworld Breach': 1,
            'Vampiric Tutor': 1,
            'Veil of Summer': 1,
            'Verdant Catacombs': 1,
            'Voice of Victory': 1,
            'Volcanic Island': 1,
            "Warrior's Oath": 1,
            'Windswept Heath': 1,
            'Wishclaw Talisman': 1,
            'Wooded Foothills': 1,
            'Worldly Tutor': 1,
        },
    },
}

