"""Build datalog/actions.dl deterministically from explicit structures.

Keyword actions (§701) — the effect verbs. Each `do_<verb>(...)` instruction
derives its result (a zone change or status change): destroy (701.8, not for
indestructible), exile (701.13), sacrifice (701.21, only what you control),
counter (701.6, a spell -> graveyard), tap/untap (701.26), fight (701.14, each
deals its power to the other), mill (701.17). The keywords are a (rule#, name)
table; the rulings are rules over the instructions + state.
"""

from __future__ import annotations

import os, sys; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root on sys.path (run as script from interpreter/)

from pathlib import Path

from interpreter.dlgen import Program

KEYWORD_ACTIONS = [
    ("701.6", "counter"), ("701.8", "destroy"), ("701.13", "exile"),
    ("701.14", "fight"), ("701.17", "mill"), ("701.21", "sacrifice"), ("701.26", "tap_untap"),
]

INPUTS = [
    ("do_destroy", [("o", "symbol")]),
    ("do_exile", [("o", "symbol")]),
    ("do_sacrifice", [("p", "symbol"), ("o", "symbol")]),
    ("do_counter", [("s", "symbol")]),
    ("do_tap", [("o", "symbol")]),
    ("do_untap", [("o", "symbol")]),
    ("do_fight", [("a", "symbol"), ("b", "symbol")]),
    ("do_mill", [("p", "symbol"), ("n", "number")]),
    ("indestructible", [("o", "symbol")]),
    ("controls", [("p", "symbol"), ("o", "symbol")]),
    ("power", [("c", "symbol"), ("n", "number")]),
    ("toughness", [("c", "symbol"), ("n", "number")]),
]

EXPECT_DECLS = [
    ("expect_moves", [("o", "symbol"), ("z", "symbol")]),
    ("expect_no_move", [("o", "symbol")]),
    ("expect_becomes", [("o", "symbol"), ("st", "symbol")]),
    ("expect_fight_dies", [("c", "symbol")]),
    ("expect_fight_survives", [("c", "symbol")]),
    ("expect_milled", [("p", "symbol"), ("n", "number")]),
]
CHECKS = [
    ("moves", "expect_moves(O, Z)", "miss", "moves_to(O, Z)"),
    ("no_move", "expect_no_move(O)", "hit", "moves_to(O, _)"),
    ("becomes", "expect_becomes(O, St)", "miss", "becomes(O, St)"),
    ("fight_dies", "expect_fight_dies(C)", "miss", "fight_lethal(C)"),
    ("fight_survives", "expect_fight_survives(C)", "hit", "fight_lethal(C)"),
    ("milled", "expect_milled(P, N)", "miss", "milled(P, N)", "P", '"-"'),
]

SCENARIOS = [
    # 701.8 destroy: a creature goes to the graveyard; an indestructible one does not.
    'do_destroy("thopter")', 'expect_moves("thopter", "graveyard")',
    'do_destroy("darksteel")', 'indestructible("darksteel")', 'expect_no_move("darksteel")',
    # 701.13 exile.
    'do_exile("ghost")', 'expect_moves("ghost", "exile")',
    # 701.21 sacrifice: you sacrifice what you control; you can't sacrifice an opponent's.
    'do_sacrifice("alice", "clue")', 'controls("alice", "clue")', 'expect_moves("clue", "graveyard")',
    'do_sacrifice("alice", "enemy")', 'controls("bob", "enemy")', 'expect_no_move("enemy")',
    # 701.6 counter: a spell on the stack goes to the graveyard.
    'do_counter("bolt")', 'expect_moves("bolt", "graveyard")',
    # 701.26 tap / untap.
    'do_tap("knight")', 'expect_becomes("knight", "tapped")',
    'do_untap("elf")', 'expect_becomes("elf", "untapped")',
    # 701.14 fight: a 2/2 and a 3/3 fight -> the 2/2 dies, the 3/3 survives.
    'do_fight("grizzly", "ogre")',
    'power("grizzly", 2)', 'toughness("grizzly", 2)', 'power("ogre", 3)', 'toughness("ogre", 3)',
    'expect_fight_dies("grizzly")', 'expect_fight_survives("ogre")',
    # 701.17 mill: the top 3 of a library go to the graveyard.
    'do_mill("alice", 3)', 'expect_milled("alice", 3)',
]


def build() -> str:
    p = Program()
    p.comment("actions.dl — GENERATED by build_actions.py (deterministic). Do not edit by hand.")
    p.comment("MTG keyword actions (§701): each effect verb's result over the game state.")
    p.blank()
    p.decl("keyword_action", [("rule", "symbol"), ("name", "symbol")])
    p.facts([f'keyword_action("{rule}", "{name}")' for rule, name in KEYWORD_ACTIONS])
    p.blank()
    for name, cols in INPUTS:
        p.decl(name, cols)
    p.blank()

    # zone changes
    p.decl("moves_to", [("o", "symbol"), ("z", "symbol")])
    p.rule('moves_to(O, "graveyard")', ["do_destroy(O)", "!indestructible(O)"], note="§701.8 — indestructible isn't destroyed")
    p.rule('moves_to(O, "exile")', ["do_exile(O)"], note="§701.13")
    p.rule('moves_to(O, "graveyard")', ["do_sacrifice(P, O)", "controls(P, O)"], note="§701.21 — you sacrifice what you control")
    p.rule('moves_to(S, "graveyard")', ["do_counter(S)"], note="§701.6 — a countered spell")
    p.blank()
    # status changes
    p.decl("becomes", [("o", "symbol"), ("st", "symbol")])
    p.rule('becomes(O, "tapped")', ["do_tap(O)"], note="§701.26")
    p.rule('becomes(O, "untapped")', ["do_untap(O)"])
    p.blank()
    # §701.14 fight — each creature deals damage equal to its power to the other.
    p.decl("fight_deals", [("source", "symbol"), ("target", "symbol"), ("n", "number")])
    p.rule("fight_deals(A, B, N)", ["do_fight(A, B)", "power(A, N)"])
    p.rule("fight_deals(B, A, N)", ["do_fight(A, B)", "power(B, N)"])
    p.decl("fight_lethal", [("c", "symbol")])
    p.rule("fight_lethal(C)", ["fight_deals(_, C, D)", "toughness(C, T)", "D >= T"])
    p.blank()
    # §701.17 mill — N cards from the top of the library to the graveyard.
    p.decl("milled", [("p", "symbol"), ("n", "number")])
    p.rule("milled(P, N)", ["do_mill(P, N)"])
    p.blank()

    p.output("moves_to", "becomes", "fight_lethal", "milled")
    p.blank()
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()
    p.comment("scenarios under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/actions.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/actions.dl")


if __name__ == "__main__":
    main()
