"""Build datalog/targeting.dl deterministically from explicit structures.

Targeting (§115) and the targeting keywords: shroud (702.18), hexproof (702.11b),
protection (702.16e, the "can't be targeted" part), ward (702.21a). A spell/ability
`targets` an object; legality checks the required type and these restrictions.
"""

from __future__ import annotations

import os, sys; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root on sys.path (run as script from interpreter/)

from pathlib import Path

from interpreter.dlgen import Program

KEYWORDS = [
    ("702.18", "shroud"), ("702.11", "hexproof"), ("702.16", "protection"), ("702.21", "ward"),
]

INPUTS = [
    ("targets", [("g", "symbol"), ("source", "symbol"), ("target", "symbol")]),
    ("controls", [("p", "symbol"), ("o", "symbol")]),         # controller of source and target
    ("requires_type", [("source", "symbol"), ("t", "symbol")]),  # 115.4 "target [type]"
    ("has_type", [("o", "symbol"), ("t", "symbol")]),
    ("has_keyword", [("o", "symbol"), ("kw", "symbol")]),      # shroud / hexproof / ward
    ("protection_from", [("o", "symbol"), ("q", "symbol")]),   # 702.16
    ("source_quality", [("source", "symbol"), ("q", "symbol")]),  # e.g. the source's color
]

EXPECT_DECLS = [
    ("expect_legal", [("g", "symbol"), ("s", "symbol"), ("t", "symbol")]),
    ("expect_illegal", [("g", "symbol"), ("s", "symbol"), ("t", "symbol")]),
    ("expect_ward", [("g", "symbol"), ("t", "symbol")]),
    ("expect_no_ward", [("g", "symbol"), ("t", "symbol")]),
]
CHECKS = [
    ("legal", "expect_legal(G, S, T)", "miss", "legal_target(G, S, T)"),
    ("illegal", "expect_illegal(G, S, T)", "miss", "illegal_target(G, S, T)"),
    ("ward", "expect_ward(G, T)", "miss", "ward_triggered(G, T, _)"),
    ("no_ward", "expect_no_ward(G, T)", "hit", "ward_triggered(G, T, _)"),
]

SCENARIOS = [
    # who controls what
    'controls("bob", "bolt")', 'controls("alice", "growth")',
    'controls("alice", "bear")', 'controls("alice", "troll")', 'controls("alice", "knight_w")',
    'controls("alice", "invisible")', 'controls("alice", "guardian")', 'controls("alice", "forest")',
    # types
    'has_type("bear", "creature")', 'has_type("troll", "creature")', 'has_type("knight_w", "creature")',
    'has_type("invisible", "creature")', 'has_type("guardian", "creature")', 'has_type("forest", "land")',
    # keywords / qualities
    'has_keyword("troll", "hexproof")', 'has_keyword("invisible", "shroud")', 'has_keyword("guardian", "ward")',
    'protection_from("knight_w", "red")',
    # the sources (a red burn spell controlled by bob; a growth spell by alice)
    'requires_type("bolt", "creature")', 'source_quality("bolt", "red")',
    'requires_type("growth", "creature")',
    # g1: bob's bolt targets a plain creature -> legal.
    'targets("g1", "bolt", "bear")', 'expect_legal("g1", "bolt", "bear")',
    # g2: bob's bolt targets alice's hexproof troll -> illegal (opponent). 702.11b
    'targets("g2", "bolt", "troll")', 'expect_illegal("g2", "bolt", "troll")',
    # g3: alice's own growth targets her hexproof troll -> legal (not an opponent).
    'targets("g3", "growth", "troll")', 'expect_legal("g3", "growth", "troll")',
    # g4: red bolt targets protection-from-red knight -> illegal. 702.16e
    'targets("g4", "bolt", "knight_w")', 'expect_illegal("g4", "bolt", "knight_w")',
    # g5: bolt targets a shroud creature -> illegal (any source). 702.18
    'targets("g5", "bolt", "invisible")', 'expect_illegal("g5", "bolt", "invisible")',
    # g6: "target creature" bolt targets a land -> illegal (wrong type). 115.4
    'targets("g6", "bolt", "forest")', 'expect_illegal("g6", "bolt", "forest")',
    # g7: bob's bolt targets alice's ward creature -> targets it (legal) AND ward triggers.
    'targets("g7", "bolt", "guardian")', 'expect_legal("g7", "bolt", "guardian")', 'expect_ward("g7", "guardian")',
    # g3 also: alice's own spell on her ward creature -> ward does NOT trigger (not an opponent).
    'targets("g8", "growth", "guardian")', 'expect_no_ward("g8", "guardian")',
]


def build() -> str:
    p = Program()
    p.comment("targeting.dl — GENERATED by build_targeting.py (deterministic). Do not edit by hand.")
    p.comment("MTG targeting (§115) and targeting keywords (shroud/hexproof/protection/ward).")
    p.blank()
    p.decl("keyword", [("rule", "symbol"), ("name", "symbol")])
    p.facts([f'keyword("{rule}", "{name}")' for rule, name in KEYWORDS])
    p.blank()
    for name, cols in INPUTS:
        p.decl(name, cols)
    p.blank()

    # an opponent relation: source and target have different controllers.
    p.decl("opponent_source", [("g", "symbol"), ("source", "symbol"), ("target", "symbol")])
    p.rule("opponent_source(G, S, T)",
           ["targets(G, S, T)", "controls(SC, S)", "controls(TC, T)", "SC != TC"])
    p.blank()

    # §115.4 / §702.x — reasons a target is illegal.
    p.decl("illegal_target", [("g", "symbol"), ("s", "symbol"), ("t", "symbol")])
    p.rule("illegal_target(G, S, T)",
           ["targets(G, S, T)", "requires_type(S, Ty)", "!has_type(T, Ty)"], note="§115.4 wrong type")
    p.rule("illegal_target(G, S, T)",
           ["targets(G, S, T)", 'has_keyword(T, "shroud")'], note="§702.18 shroud — any source")
    p.rule("illegal_target(G, S, T)",
           ['has_keyword(T, "hexproof")', "opponent_source(G, S, T)"], note="§702.11b hexproof — opponents")
    p.rule("illegal_target(G, S, T)",
           ["targets(G, S, T)", "protection_from(T, Q)", "source_quality(S, Q)"], note="§702.16e protection")
    p.decl("legal_target", [("g", "symbol"), ("s", "symbol"), ("t", "symbol")])
    p.rule("legal_target(G, S, T)", ["targets(G, S, T)", "!illegal_target(G, S, T)"], note="§115.4")
    p.blank()

    # §702.21a — ward triggers when a permanent becomes the target of an opponent's spell/ability.
    p.decl("ward_triggered", [("g", "symbol"), ("t", "symbol"), ("s", "symbol")])
    p.rule("ward_triggered(G, T, S)", ['has_keyword(T, "ward")', "opponent_source(G, S, T)"], note="§702.21a")
    p.blank()

    p.output("legal_target", "illegal_target", "ward_triggered")
    p.blank()
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()
    p.comment("scenarios under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/targeting.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/targeting.dl")


if __name__ == "__main__":
    main()
