"""Build datalog/triggers.dl deterministically from explicit structures.

Triggered abilities (§603): an ability with `has_trigger(ability, source, event)`
fires when a matching game event occurs (§603.2), is put on the stack at the next
priority (§603.3), and is controlled by its source's controller (§603.3a). Covers
the common trigger patterns: ETB self/other (603.6a), dies self/other, attacks,
beginning of your upkeep, and casting a spell (prowess-style).
"""

from __future__ import annotations

import os, sys; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root on sys.path (run as script from interpreter/)

from pathlib import Path

from interpreter.dlgen import Program

# the trigger-event taxonomy this slice covers.
EVENTS = ["etb_self", "etb_other", "dies_self", "dies_other", "attacks_self", "upkeep", "cast_spell"]

INPUTS = [
    ("has_trigger", [("ability", "symbol"), ("source", "symbol"), ("event", "symbol")]),
    ("controls", [("p", "symbol"), ("source", "symbol")]),
    ("active_player", [("p", "symbol")]),
    # game events that occurred (supplied by the rest of the engine in integration)
    ("entered", [("c", "symbol")]),       # a permanent entered the battlefield
    ("died", [("c", "symbol")]),          # a creature died
    ("attacked", [("c", "symbol")]),      # a creature was declared an attacker
    ("step_began", [("s", "symbol")]),    # a step began
    ("cast_by", [("p", "symbol"), ("spell", "symbol")]),   # a player cast a spell
]

EXPECT_DECLS = [
    ("expect_triggers", [("a", "symbol")]),
    ("expect_no_trigger", [("a", "symbol")]),
    ("expect_on_stack", [("a", "symbol")]),
    ("expect_controller", [("a", "symbol"), ("p", "symbol")]),
]
CHECKS = [
    ("triggers", "expect_triggers(A)", "miss", "triggers(A)"),
    ("no_trigger", "expect_no_trigger(A)", "hit", "triggers(A)"),
    ("on_stack", "expect_on_stack(A)", "miss", "goes_on_stack(A)"),
    ("controller", "expect_controller(A, P)", "miss", "trigger_controller(A, P)"),
]

SCENARIOS = [
    # an elemental enters: its own ETB trigger AND a soul-warden's "another creature enters" trigger.
    'entered("elemental")',
    'has_trigger("elem_draw", "elemental", "etb_self")', 'controls("alice", "elemental")',
    'has_trigger("warden_gain", "soul_warden", "etb_other")', 'controls("bob", "soul_warden")',
    'expect_triggers("elem_draw")', 'expect_triggers("warden_gain")',
    'expect_on_stack("elem_draw")', 'expect_controller("elem_draw", "alice")',
    # a dormant creature that did NOT enter -> its ETB trigger doesn't fire.
    'has_trigger("dormant", "sleeper", "etb_self")', 'controls("alice", "sleeper")', 'expect_no_trigger("dormant")',
    # a creature dies: blood artist (another creature dies) + the dying creature's own dies trigger.
    'died("victim")',
    'has_trigger("artist_drain", "blood_artist", "dies_other")', 'controls("alice", "blood_artist")', 'expect_triggers("artist_drain")',
    'died("reveler")',
    'has_trigger("reveler_party", "reveler", "dies_self")', 'controls("bob", "reveler")', 'expect_triggers("reveler_party")',
    # a creature attacks -> its attack trigger.
    'attacked("raptor")',
    'has_trigger("raptor_pump", "raptor", "attacks_self")', 'controls("alice", "raptor")', 'expect_triggers("raptor_pump")',
    # beginning of alice's upkeep -> her upkeep trigger fires; bob's "your upkeep" trigger does NOT.
    'step_began("upkeep")', 'active_player("alice")',
    'has_trigger("phyrexian_dmg", "phyrexian", "upkeep")', 'controls("alice", "phyrexian")', 'expect_triggers("phyrexian_dmg")',
    'has_trigger("bob_upkeep", "bob_thing", "upkeep")', 'controls("bob", "bob_thing")', 'expect_no_trigger("bob_upkeep")',
    # alice casts a spell -> her prowess-style trigger; bob's does not.
    'cast_by("alice", "bolt")',
    'has_trigger("monastery_prowess", "monastery", "cast_spell")', 'controls("alice", "monastery")', 'expect_triggers("monastery_prowess")',
    'has_trigger("bob_prowess", "bob_mystic", "cast_spell")', 'controls("bob", "bob_mystic")', 'expect_no_trigger("bob_prowess")',
]


def build() -> str:
    p = Program()
    p.comment("triggers.dl — GENERATED by build_triggers.py (deterministic). Do not edit by hand.")
    p.comment("MTG triggered abilities (§603): match a game event -> put on the stack at next priority.")
    p.blank()
    p.decl("trigger_event", [("name", "symbol")])
    p.facts([f'trigger_event("{e}")' for e in EVENTS])
    p.blank()
    for name, cols in INPUTS:
        p.decl(name, cols)
    p.blank()

    # §603.2 — an ability triggers when a game event matches its trigger condition.
    p.decl("triggers", [("ability", "symbol")])
    p.rule("triggers(A)", ['has_trigger(A, S, "etb_self")', "entered(S)"], note="§603.6a — this enters")
    p.rule("triggers(A)", ['has_trigger(A, S, "etb_other")', "entered(C)", "C != S"], note="§603.6a — another permanent enters")
    p.rule("triggers(A)", ['has_trigger(A, S, "dies_self")', "died(S)"])
    p.rule("triggers(A)", ['has_trigger(A, S, "dies_other")', "died(C)", "C != S"])
    p.rule("triggers(A)", ['has_trigger(A, S, "attacks_self")', "attacked(S)"])
    p.rule("triggers(A)", ['has_trigger(A, S, "upkeep")', 'step_began("upkeep")', "controls(P, S)", "active_player(P)"],
           note="“at the beginning of your upkeep” — the active player's")
    p.rule("triggers(A)", ['has_trigger(A, S, "cast_spell")', "cast_by(P, _)", "controls(P, S)"])
    p.blank()

    # §603.3 — a triggered ability is put on the stack at the next priority.
    p.decl("goes_on_stack", [("ability", "symbol")])
    p.rule("goes_on_stack(A)", ["triggers(A)"], note="§603.3")
    # §603.3a — controlled by its source's controller at the time it triggered.
    p.decl("trigger_controller", [("ability", "symbol"), ("p", "symbol")])
    p.rule("trigger_controller(A, P)", ["triggers(A)", "has_trigger(A, S, _)", "controls(P, S)"], note="§603.3a")
    p.blank()

    p.output("triggers", "goes_on_stack", "trigger_controller")
    p.blank()
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()
    p.comment("scenarios under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/triggers.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/triggers.dl")


if __name__ == "__main__":
    main()
