"""Build datalog/abilities.dl deterministically from explicit structures.

Activated abilities (§602): "[Cost]: [Effect]". A player can activate one when
they have priority (§117.1b) and can pay the cost (§602.2): tap costs need an
untapped source (and a creature's {T} ability needs no summoning sickness, §302.6),
mana costs need enough mana (§118.3), and "activate only as a sorcery" abilities
follow sorcery timing (§602.5d).
"""

from __future__ import annotations

import os, sys; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root on sys.path (run as script from interpreter/)

from pathlib import Path

from interpreter.dlgen import Program

INPUTS = [
    ("has_ability", [("source", "symbol"), ("ability", "symbol")]),
    ("ability_tap", [("ability", "symbol")]),         # {T} in the cost
    ("ability_mana", [("ability", "symbol"), ("n", "number")]),   # mana value of the cost (0 if free)
    ("ability_sorcery", [("ability", "symbol")]),     # "activate only as a sorcery"
    ("controls", [("p", "symbol"), ("source", "symbol")]),
    ("is_creature", [("source", "symbol")]),
    ("tapped", [("source", "symbol")]),
    ("summoning_sick", [("source", "symbol")]),
    ("has_priority", [("p", "symbol")]),
    ("active_player", [("p", "symbol")]),
    ("current_step", [("s", "symbol")]),
    ("mana_available", [("p", "symbol"), ("n", "number")]),
    ("on_stack", [("o", "symbol"), ("pos", "number")]),
]

EXPECT_DECLS = [
    ("expect_activate", [("p", "symbol"), ("a", "symbol")]),
    ("expect_no_activate", [("p", "symbol"), ("a", "symbol")]),
]
CHECKS = [
    ("activate", "expect_activate(P, A)", "miss", "can_activate(P, A)"),
    ("no_activate", "expect_no_activate(P, A)", "hit", "can_activate(P, A)"),
]

SCENARIOS = [
    # the turn: alice's precombat main, she has priority, a spell is on the stack, 3 mana.
    'current_step("precombat_main")', 'active_player("alice")', 'has_priority("alice")',
    'mana_available("alice", 3)', 'on_stack("pending", 0)',
    # a mana elf ({T}: add G), untapped and not sick -> activatable.
    'has_ability("llanowar", "ll")', 'ability_tap("ll")', 'ability_mana("ll", 0)', 'is_creature("llanowar")', 'controls("alice", "llanowar")',
    'expect_activate("alice", "ll")',
    # a tapped elf -> its {T} ability can't be activated (already tapped).
    'has_ability("tapped_elf", "te")', 'ability_tap("te")', 'ability_mana("te", 0)', 'is_creature("tapped_elf")', 'controls("alice", "tapped_elf")', 'tapped("tapped_elf")',
    'expect_no_activate("alice", "te")',
    # a summoning-sick elf -> its {T} ability can't be activated (302.6).
    'has_ability("sick_elf", "se")', 'ability_tap("se")', 'ability_mana("se", 0)', 'is_creature("sick_elf")', 'controls("alice", "sick_elf")', 'summoning_sick("sick_elf")',
    'expect_no_activate("alice", "se")',
    # a {1}{G} pump (cost 2) -> affordable with 3 mana.
    'has_ability("warrior", "pump")', 'ability_mana("pump", 2)', 'controls("alice", "warrior")',
    'expect_activate("alice", "pump")',
    # a cost-5 ability -> NOT affordable with 3 mana.
    'has_ability("titan", "bigpump")', 'ability_mana("bigpump", 5)', 'controls("alice", "titan")',
    'expect_no_activate("alice", "bigpump")',
    # a sorcery-speed ability -> blocked here because the stack is not empty (602.5d).
    'has_ability("walker", "ult")', 'ability_mana("ult", 0)', 'ability_sorcery("ult")', 'controls("alice", "walker")',
    'expect_no_activate("alice", "ult")',
]


def build() -> str:
    p = Program()
    p.comment("abilities.dl — GENERATED by build_abilities.py (deterministic). Do not edit by hand.")
    p.comment("MTG activated abilities (§602): can a player legally activate one now?")
    p.blank()
    for name, cols in INPUTS:
        p.decl(name, cols)
    p.blank()
    p.decl("main_phase", [("s", "symbol")])
    p.facts(['main_phase("precombat_main")', 'main_phase("postcombat_main")'])
    p.blank()

    # §118.3 — can the controller pay the mana cost?
    p.decl("can_afford", [("p", "symbol"), ("a", "symbol")])
    p.rule("can_afford(P, A)", ["has_ability(S, A)", "controls(P, S)", "ability_mana(A, C)", "mana_available(P, M)", "M >= C"])
    p.blank()
    # a tap cost is blocked if the source is already tapped, or (for a creature) it's summoning-sick.
    p.decl("tap_blocked", [("a", "symbol")])
    p.rule("tap_blocked(A)", ["has_ability(S, A)", "ability_tap(A)", "tapped(S)"], note="§602.2 — {T} needs an untapped source")
    p.rule("tap_blocked(A)", ["has_ability(S, A)", "ability_tap(A)", "is_creature(S)", "summoning_sick(S)"], note="§302.6")
    p.blank()
    # a sorcery-speed ability is blocked unless it's your main phase with an empty stack.
    p.decl("timing_blocked", [("a", "symbol")])
    p.rule("timing_blocked(A)", ["has_ability(_, A)", "ability_sorcery(A)", "current_step(St)", "!main_phase(St)"], note="§602.5d")
    p.rule("timing_blocked(A)", ["has_ability(_, A)", "ability_sorcery(A)", "on_stack(_, _)"])
    p.rule("timing_blocked(A)", ["has_ability(S, A)", "ability_sorcery(A)", "controls(P, S)", "!active_player(P)"])
    p.blank()
    # §117.1b / §602.2 — activatable: you control it, have priority, can pay, no block.
    p.decl("can_activate", [("p", "symbol"), ("a", "symbol")])
    p.rule("can_activate(P, A)",
           ["has_ability(S, A)", "controls(P, S)", "has_priority(P)", "can_afford(P, A)", "!tap_blocked(A)", "!timing_blocked(A)"])
    p.blank()

    p.output("can_activate")
    p.blank()
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()
    p.comment("scenario under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/abilities.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/abilities.dl")


if __name__ == "__main__":
    main()
