"""Build datalog/combat.dl deterministically from explicit structures.

§508 (declare attackers), §509 (declare blockers), §510 (combat damage).
Thin: single blocker per attacker; summoning sickness (302.6) and combat
keywords (first strike/trample/§702) deferred.
"""

from __future__ import annotations

import os, sys; sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # repo root on sys.path (run as script from interpreter/)

from pathlib import Path

from interpreter.dlgen import Program

INPUTS = [
    ("g_active", [("g", "symbol"), ("p", "symbol")]),
    ("controls", [("g", "symbol"), ("p", "symbol"), ("c", "symbol")]),
    ("untapped", [("g", "symbol"), ("c", "symbol")]),
    ("is_creature", [("g", "symbol"), ("c", "symbol")]),
    ("is_player", [("p", "symbol")]),
    ("power", [("c", "symbol"), ("n", "number")]),
    ("toughness", [("c", "symbol"), ("n", "number")]),
    ("attacks", [("g", "symbol"), ("attacker", "symbol"), ("defender", "symbol")]),
    ("blocks", [("g", "symbol"), ("blocker", "symbol"), ("attacker", "symbol")]),
]

EXPECT_DECLS = [
    ("expect_can_attack", [("g", "symbol"), ("c", "symbol")]),
    ("expect_no_attack", [("g", "symbol"), ("c", "symbol")]),
    ("expect_can_block", [("g", "symbol"), ("c", "symbol")]),
    ("expect_dmg_player", [("g", "symbol"), ("p", "symbol"), ("n", "number")]),
    ("expect_lethal", [("g", "symbol"), ("c", "symbol")]),
    ("expect_no_lethal", [("g", "symbol"), ("c", "symbol")]),
]
CHECKS = [
    ("can_attack", "expect_can_attack(G, C)", "miss", "can_attack(G, C)"),
    ("no_attack", "expect_no_attack(G, C)", "hit", "can_attack(G, C)"),
    ("can_block", "expect_can_block(G, C)", "miss", "can_block(G, C)"),
    ("dmg_player", "expect_dmg_player(G, P, N)", "miss", "dmg_to_player(G, P, N)"),
    ("lethal", "expect_lethal(G, C)", "miss", "combat_lethal(G, C)"),
    ("no_lethal", "expect_no_lethal(G, C)", "hit", "combat_lethal(G, C)"),
]

SCENARIOS = [
    'is_player("bob")',
    'power("grizzly", 2)', 'toughness("grizzly", 2)',
    'power("bear", 2)', 'toughness("bear", 2)',
    'power("wall", 0)', 'toughness("wall", 4)',
    'power("tapped_c", 3)', 'toughness("tapped_c", 3)',
    # g1: declaration legality.
    'g_active("g1", "alice")', 'controls("g1", "alice", "grizzly")', 'is_creature("g1", "grizzly")', 'untapped("g1", "grizzly")',
    'controls("g1", "alice", "tapped_c")', 'is_creature("g1", "tapped_c")',
    'controls("g1", "bob", "wall")', 'is_creature("g1", "wall")', 'untapped("g1", "wall")',
    'expect_can_attack("g1", "grizzly")', 'expect_no_attack("g1", "tapped_c")',
    'expect_no_attack("g1", "wall")', 'expect_can_block("g1", "wall")',
    # g2: unblocked attacker -> player takes 2.
    'g_active("g2", "alice")', 'attacks("g2", "grizzly", "bob")', 'expect_dmg_player("g2", "bob", 2)',
    # g3: 2/2 vs 2/2 -> both lethal.
    'g_active("g3", "alice")', 'attacks("g3", "grizzly", "bob")', 'blocks("g3", "bear", "grizzly")',
    'expect_lethal("g3", "grizzly")', 'expect_lethal("g3", "bear")',
    # g4: 2/2 vs 0/4 wall -> neither lethal.
    'g_active("g4", "alice")', 'attacks("g4", "grizzly", "bob")', 'blocks("g4", "wall", "grizzly")',
    'expect_no_lethal("g4", "wall")', 'expect_no_lethal("g4", "grizzly")',
]


def build() -> str:
    p = Program()
    p.comment("combat.dl — GENERATED by build_combat.py (deterministic). Do not edit by hand.")
    p.comment("MTG combat: declaring attackers/blockers (§508/§509) and combat damage (§510).")
    p.blank()
    for name, cols in INPUTS:
        p.decl(name, cols)
    p.blank()
    p.decl("can_attack", [("g", "symbol"), ("c", "symbol")])
    p.rule("can_attack(G, C)", ["g_active(G, P)", "controls(G, P, C)", "is_creature(G, C)", "untapped(G, C)"],
           note="§508.1a — untapped creature the active player controls")
    p.decl("can_block", [("g", "symbol"), ("c", "symbol")])
    p.rule("can_block(G, C)", ["is_creature(G, C)", "untapped(G, C)", "controls(G, P, C)", "!g_active(G, P)"],
           note="§509.1a — untapped creature a defending (non-active) player controls")
    p.blank()
    p.decl("blocked", [("g", "symbol"), ("attacker", "symbol")])
    p.rule("blocked(G, A)", ["blocks(G, _, A)"])
    p.decl("unblocked", [("g", "symbol"), ("attacker", "symbol")])
    p.rule("unblocked(G, A)", ["attacks(G, A, _)", "!blocked(G, A)"], note="§509.2")
    p.blank()
    p.decl("dmg_to_player", [("g", "symbol"), ("defender", "symbol"), ("n", "number")])
    p.rule("dmg_to_player(G, D, N)", ["attacks(G, A, D)", "is_player(D)", "unblocked(G, A)", "power(A, N)"],
           note="§510.1c — an unblocked creature deals its power to the player")
    p.decl("combat_dmg", [("g", "symbol"), ("source", "symbol"), ("target", "symbol"), ("n", "number")])
    p.rule("combat_dmg(G, A, B, N)", ["blocks(G, B, A)", "power(A, N)"], note="§510.1c — attacker -> blocker")
    p.rule("combat_dmg(G, B, A, N)", ["blocks(G, B, A)", "power(B, N)"], note="blocker -> attacker")
    p.blank()
    p.decl("marked_damage", [("g", "symbol"), ("c", "symbol"), ("total", "number")])
    p.rule("marked_damage(G, C, T)", ["combat_dmg(G, _, C, _)", "T = sum N : { combat_dmg(G, _, C, N) }"],
           note="§510.2 — combat damage dealt simultaneously")
    p.decl("combat_lethal", [("g", "symbol"), ("c", "symbol")])
    p.rule("combat_lethal(G, C)", ["marked_damage(G, C, D)", "toughness(C, T)", "T > 0", "D >= T"],
           note="§704.5g — lethal combat damage (feeds the SBA)")
    p.blank()
    p.output("can_attack", "dmg_to_player", "marked_damage", "combat_lethal")
    p.blank()
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()
    p.comment("scenarios under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/combat.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/combat.dl")


if __name__ == "__main__":
    main()
