"""Build datalog/turn.dl deterministically from explicit structures.

The STRUCTURES (the rules' content) are the data below; dlgen lowers them to
Datalog with no interpretation. §500 turn structure, §117 priority.
"""

from __future__ import annotations

import os, sys  # put repo root + packages/ on sys.path (file relocated; find root by the datalog/ marker)
_r = os.path.dirname(os.path.abspath(__file__))
while _r != os.path.dirname(_r) and not os.path.isdir(os.path.join(_r, "datalog")):
    _r = os.path.dirname(_r)
for _p in (_r, os.path.join(_r, "packages")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from pathlib import Path

from interpreter.dlgen import Program
from interpreter.build_turn_actions import no_priority_steps

# === the structures (auditable data) =========================================
# §500.1 — a turn's phases/steps in order. (Main phases occupy one position.)
STEPS: list[tuple[str, str]] = [
    ("untap", "beginning"),            # 502
    ("upkeep", "beginning"),           # 503
    ("draw", "beginning"),             # 504
    ("precombat_main", "precombat_main"),
    ("begin_combat", "combat"),        # 507
    ("declare_attackers", "combat"),   # 508
    ("declare_blockers", "combat"),    # 509
    ("combat_damage", "combat"),       # 510
    ("end_combat", "combat"),          # 511
    ("postcombat_main", "postcombat_main"),
    ("end_step", "ending"),            # 513
    ("cleanup", "ending"),             # 514
]
# §502.4 / §514.3 — steps where players do NOT receive priority, INTERPRETED from rules.txt.
NO_PRIORITY: list[str] = no_priority_steps()

# conformance fixtures: each scenario is plain facts (data).
SCENARIOS: list[str] = [
    # sequence (500.1) and priority windows (500.3 / 502.4 / 514.3)
    'expect_next("untap", "upkeep")', 'expect_next("draw", "precombat_main")',
    'expect_next("combat_damage", "end_combat")', 'expect_next("end_step", "cleanup")',
    'expect_priority_step("upkeep")', 'expect_priority_step("draw")', 'expect_priority_step("end_step")',
    'expect_no_priority("untap")', 'expect_no_priority("cleanup")',
    # g1: untap (no priority); alice untaps her tapped permanent, then advances.
    'gstate("g1", "alice", "untap")', 'g_tapped_perm("g1", "alice", "c1")',
    'expect_untap("g1", "c1")', 'expect_no_receives("g1")', 'expect_advance("g1", "upkeep")',
    # g2: draw; bob draws, gets priority, (empty stack + all passed) advances.
    'gstate("g2", "bob", "draw")', 'g_stack_empty("g2")', 'g_all_passed("g2")',
    'expect_draw("g2", "bob")', 'expect_receives("g2", "bob")', 'expect_advance("g2", "precombat_main")',
    # g3: upkeep, not all players passed -> step does not end.
    'gstate("g3", "alice", "upkeep")', 'g_stack_empty("g3")',
    'expect_receives("g3", "alice")', 'expect_no_advance("g3")',
]

# conformance checks: (kind, expect-relation+args, polarity, target-relation+args)
# polarity "miss" = fail when target absent; "hit" = fail when target present.
CHECKS = [
    ("next", "expect_next(A, B)", "miss", "next_step(A, B)"),
    ("priority_step", "expect_priority_step(S)", "miss", "priority_step(S)"),
    ("no_priority", "expect_no_priority(S)", "hit", "priority_step(S)"),
    ("untap", "expect_untap(G, O)", "miss", "tb_untap(G, O)"),
    ("draw", "expect_draw(G, P)", "miss", "tb_draw(G, P)"),
    ("receives", "expect_receives(G, P)", "miss", "receives_priority(G, P)"),
    ("no_receives", "expect_no_receives(G)", "hit", "receives_priority(G, _)"),
    ("advance", "expect_advance(G, N)", "miss", "advance_to(G, N)"),
    ("no_advance", "expect_no_advance(G)", "hit", "advance_to(G, _)"),
]
EXPECT_DECLS = [
    ("expect_next", [("cur", "symbol"), ("nxt", "symbol")]),
    ("expect_priority_step", [("name", "symbol")]),
    ("expect_no_priority", [("name", "symbol")]),
    ("expect_untap", [("g", "symbol"), ("o", "symbol")]),
    ("expect_draw", [("g", "symbol"), ("p", "symbol")]),
    ("expect_receives", [("g", "symbol"), ("p", "symbol")]),
    ("expect_no_receives", [("g", "symbol")]),
    ("expect_advance", [("g", "symbol"), ("nxt", "symbol")]),
    ("expect_no_advance", [("g", "symbol")]),
]


def build() -> str:
    p = Program()
    p.comment("turn.dl — GENERATED by build_turn.py (deterministic). Do not edit by hand.")
    p.comment("MTG turn structure (§500) and priority (§117).")
    p.blank()

    # --- §500.1 the ordered step sequence (from the STEPS structure) ---
    p.decl("step", [("idx", "number"), ("name", "symbol"), ("phase", "symbol")])
    for i, (name, phase) in enumerate(STEPS):
        p.fact(f'step({i}, "{name}", "{phase}")')
    p.decl("next_step", [("cur", "symbol"), ("nxt", "symbol")])
    p.rule("next_step(A, B)", ["step(I, A, _)", "step(J, B, _)", "J = I + 1"],
           note="§500.1 — successive positions")
    p.blank()

    # --- §500.3/§502.4/§514.3 priority windows (from NO_PRIORITY) ---
    p.decl("no_priority_step", [("name", "symbol")])
    p.facts([f'no_priority_step("{n}")' for n in NO_PRIORITY])
    p.decl("priority_step", [("name", "symbol")])
    p.rule("priority_step(N)", ["step(_, N, _)", "!no_priority_step(N)"],
           note="§500.3 — players get priority in every step but untap/cleanup")
    p.blank()

    # --- per-game-state inputs ---
    for name, cols in [
        ("gstate", [("g", "symbol"), ("active", "symbol"), ("step", "symbol")]),
        ("g_stack_empty", [("g", "symbol")]), ("g_all_passed", [("g", "symbol")]),
        ("g_tapped_perm", [("g", "symbol"), ("p", "symbol"), ("o", "symbol")]),
    ]:
        p.decl(name, cols)
    p.blank()

    # --- derivations: turn-based actions, priority, advancement ---
    p.decl("tb_untap", [("g", "symbol"), ("o", "symbol")])
    p.rule("tb_untap(G, O)", ['gstate(G, P, "untap")', "g_tapped_perm(G, P, O)"],
           note="§502.3 — the active player untaps their permanents")
    p.decl("tb_draw", [("g", "symbol"), ("p", "symbol")])
    p.rule("tb_draw(G, P)", ['gstate(G, P, "draw")'], note="§504.1 — the active player draws")
    p.decl("receives_priority", [("g", "symbol"), ("p", "symbol")])
    p.rule("receives_priority(G, P)", ["gstate(G, P, S)", "priority_step(S)"],
           note="§117.3a — active player gets priority at the start of a priority step")
    p.decl("step_complete", [("g", "symbol"), ("step", "symbol")])
    p.rule("step_complete(G, S)", ["gstate(G, _, S)", "priority_step(S)", "g_stack_empty(G)", "g_all_passed(G)"],
           note="§500.2 — a priority step ends on empty stack + all pass")
    p.rule("step_complete(G, S)", ["gstate(G, _, S)", "no_priority_step(S)"],
           note="§500.3 — a no-priority step ends when its actions complete")
    p.decl("advance_to", [("g", "symbol"), ("nxt", "symbol")])
    p.rule("advance_to(G, N)", ["gstate(G, _, S)", "step_complete(G, S)", "next_step(S, N)"])
    p.blank()
    p.output("next_step", "priority_step", "tb_untap", "advance_to")
    p.blank()

    # --- conformance harness (generated from CHECKS) ---
    p.comment("conformance")
    p.conformance(EXPECT_DECLS, CHECKS)
    p.blank()

    # --- scenarios under test (fixture data) ---
    p.comment("scenarios under test")
    for atom in SCENARIOS:
        p.fact(atom)
    return p.text()


def main() -> None:
    Path("datalog").mkdir(exist_ok=True)
    Path("datalog/turn.dl").write_text(build(), encoding="utf-8")
    print("wrote datalog/turn.dl")


if __name__ == "__main__":
    main()
