"""Dump MTG cost notation as flat Soufflé facts, and assemble the runnable program.

This Python is intentionally a DUMB fact dumper: it parses each cost with the lark
grammar, walks the tree, and emits one `sym_opt` fact per symbol option. ALL cost
semantics live in the reviewable Datalog:
    datalog/cost_engine.dl   the rules (payability, mana value, {X}, cost mods)
    datalog/cost_tests.dl    conformance fixtures (Example: blocks)
This module just lowers the corpus costs to facts and concatenates the three into
datalog/mana.dl. Run: `souffle datalog/mana.dl -D datalog/out`.
"""

from __future__ import annotations

import os, sys  # put repo root + packages/ on sys.path (file relocated; find root by the datalog/ marker)
_r = os.path.dirname(os.path.abspath(__file__))
while _r != os.path.dirname(_r) and not os.path.isdir(os.path.join(_r, "datalog")):
    _r = os.path.dirname(_r)
for _p in (_r, os.path.join(_r, "packages")):
    if _p not in sys.path:
        sys.path.insert(0, _p)


import re
from pathlib import Path

from interpreter.cost_grammar import (EnergySym, GenericSym, Hybrid, LifeSym, ManaSym,
                          SnowSym, VarSym, parse_cost)
from interpreter.preprocess import cost_token
from interpreter.rules_parser import split

DATALOG = Path("datalog")


def options(sym):
    """A cost symbol's options as (kind, arg, num); None for {X} (see xcost)."""
    if isinstance(sym, GenericSym):
        return [("generic", "", sym.n)]
    if isinstance(sym, ManaSym):
        return [("colorless", "", 0)] if sym.pip == "C" else [("color", sym.pip.lower(), 0)]
    if isinstance(sym, SnowSym):
        return [("snow", "", 0)]
    if isinstance(sym, LifeSym):
        return [("life", "", sym.life)]
    if isinstance(sym, EnergySym):
        return [("energy", "", sym.amount)]
    if isinstance(sym, Hybrid):
        return [opt for o in sym.opts for opt in options(o)]
    return None   # VarSym


def cost_expressions(rules_path: Path) -> list[str]:
    """Every distinct {..} cost expression appearing in the rules body."""
    doc = split(rules_path.read_text(encoding="utf-8"))
    exprs: set[str] = set()
    for s in doc.sections:
        for g in s.groups:
            for r in g.rules:
                texts = [r.text, *r.examples]
                texts += [t for sr in r.subrules for t in [sr.text, *sr.examples]]
                for t in texts:
                    exprs.update(re.findall(r"(?:\{[^{}]+\})+", t))
    return sorted(exprs)


def cost_facts(rules_path: Path) -> tuple[str, dict]:
    """Lower each parseable cost to sym_opt / xcost facts."""
    lines = ["", "// === cost facts transpiled from rules.txt ====================="]
    parsed = x_costs = skipped = 0
    seen: set[str] = set()
    for expr in cost_expressions(rules_path):
        try:
            symbols = parse_cost(expr)
        except Exception:
            skipped += 1
            continue
        name = cost_token(expr)
        if name in seen:
            continue
        seen.add(name)
        parsed += 1
        base = [s for s in symbols if not isinstance(s, VarSym)]
        coeff = sum(isinstance(s, VarSym) for s in symbols)
        lines.append(f'cost("{name}"). nsym("{name}", {len(base)}).   // {expr}')
        for i, sym in enumerate(base):
            for o, (kind, arg, num) in enumerate(options(sym)):
                lines.append(f'sym_opt("{name}", {i}, {o}, "{kind}", "{arg}", {num}).')
        if coeff:
            x_costs += 1
            lines.append(f'xcost("{name}", {coeff}).')
    report = {"parsed_and_modeled": parsed, "of which {X} costs": x_costs,
              "skipped_non_mana": skipped}
    return "\n".join(lines), report


BANNER = ("// mana.dl — GENERATED by datalog_gen.py (deterministic). Do not edit by hand.\n"
          "// Assembled from: cost_engine.dl (static) + cost facts transpiled from\n"
          "// rules.txt + cost_tests.dl (static). Regenerate/verify with build.py.\n")


def main() -> None:
    facts, report = cost_facts(Path("rules.txt"))
    program = "\n".join([
        BANNER,
        (DATALOG / "cost_engine.dl").read_text(),
        facts,
        (DATALOG / "cost_tests.dl").read_text(),
    ])
    (DATALOG / "mana.dl").write_text(program)
    print("wrote datalog/mana.dl")
    for k, v in report.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
