#!/usr/bin/env bash
# make_data_bundle.sh — package the two big, platform-INDEPENDENT runtime artifacts (the compiled card
# facts + the oracle corpus) into mtg-data.tar.gz and (optionally) publish them as a GitHub Release asset
# that the release CI downloads. These are generated by the interpreter pipeline over MTGJSON and are
# gitignored, so they aren't in a fresh clone — the wheel jobs fetch this bundle instead of regenerating.
#
# Run locally (from the repo root), where the artifacts already exist:
#     bash packaging/make_data_bundle.sh              # just build mtg-data.tar.gz
#     bash packaging/make_data_bundle.sh --publish    # build + upload to the `data` GitHub Release
#
# Refresh this whenever cards.dl / oracle_corpus.json change (a rebuild of the card data). The CI reads a
# rolling release named `data` (see .github/workflows/release.yml DATA_RELEASE); --publish replaces its asset.
set -euo pipefail

HERE="$(cd "$(dirname "$0")/.." && pwd)"
cd "$HERE"

FILES=(datalog/cards.dl mtgjson/oracle_corpus.json)
for f in "${FILES[@]}"; do
  [[ -f "$f" ]] || { echo "missing $f — build the card data first (interpreter/build_cards.py + build_oracle_corpus.py)"; exit 1; }
done

OUT="mtg-data.tar.gz"
tar czf "$OUT" "${FILES[@]}"     # relative paths, so `tar xzf` at the repo root drops them back into place
echo "built $OUT ($(du -h "$OUT" | cut -f1)) containing: ${FILES[*]}"

if [[ "${1:-}" == "--publish" ]]; then
  TAG="${DATA_RELEASE:-data}"
  command -v gh >/dev/null || { echo "gh CLI not found — install it or upload $OUT to the '$TAG' release manually"; exit 1; }
  if gh release view "$TAG" >/dev/null 2>&1; then
    gh release upload "$TAG" "$OUT" --clobber
  else
    gh release create "$TAG" "$OUT" -t "python-mtg data artifacts" \
      -n "Platform-independent runtime data (cards.dl + oracle_corpus.json) consumed by the wheel-build CI. Rolling."
  fi
  echo "published $OUT to the '$TAG' release"
fi
